### ISSUE TITLE
input (soft)enums : réordonner plutôt que filtrer ou montrer la liste des choix ?

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#104]
Les champs enums propose une liste de valeurs possible quand ils sont vides et que l'on clique dessus.
Quand on tape une valeur la liste est filtrée.
Quand une valeur est acceptée, et que l'on ckique dessus logiquement on ne voit pas les autres choix.

C'est un problème car on peut hésiter et voir les alternatives est important même si on a rempli le champs une première fois.

Il faut trouver un moyen de montrer les alternatives.

Je vois deux solutions: 

1. réordonner la liste des propositions plutôt que de la filtrer. On met en haut la solution qui matche et on renvoi en bas de liste ce qui ne matche pas.
2. ajouter un bouton qui permet d'afficher la liste des options
3. d'autres idées ? 

La première option semble la plus simple à faire à mes yeux.
A voir

**Comment by paulgirard** [comment]
relates #167

**Comment by naholyr** [comment]
Le filtrage est remplacé par un tri, utilisant la distance de [Damerau-Levenshtein](http://yomguithereal.github.io/talisman/metrics/distance#damerau-levenshtein). Ce sera sûrement à revoir pour le début de la frappe car avec 1 ou 2 caractères ça donne des résultats peu pertinents. Je livre déjà ça pour que vous puissiez tester plus avant.

Au passage, la langue n'était pas utilisée pour le filtrage des labels, c'est corrigé.
