### ISSUE TITLE
rôles centraux

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#105]
A ce jour les rôles centraux n'ont pas d'accès spécifique.

- [x]  les règles de périmètres/rôles côté serveur gére ces deux cas: central_admin et central_reader ?
- [x] les objets vus par central_reader sont ils bien readonly ?
- [x] ajouter des accès spéciaux dans le home : 
    - une boite qui s 'appelle Sciences Po
    - une boite par labo
- [x] Au passage virer le bouton organisations des boites de home

**Comment by paulgirard** [comment]
idéalement il faudrait : 
- une boite qui s 'appelle Sciences Po ou Communauté scientifique
- une boite par labo

**Comment by paulgirard** [comment]
Au passage virer le bouton organisations des boites de home

**Comment by naholyr** [comment]
* Boite "sciences po" = version on filtrée
* central_* = accès à tous les labos
