### ISSUE TITLE
ajouter un lien mon CV dans la home + menu ? 

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#106]
Ce lien pointe vers le formulaire de la fiche de la personne connectée

**Comment by Yomguithereal** [comment]
Je ne trouve pas la route client correspondant à un formulaire unique. Est-ce qu'il faut afficher la fiche en dessous du tableau ou juste la fiche?

**Comment by paulgirard** [comment]
La route /people/peopleId?organization=ordId (scope)

Juste le CV ce qui apparaît à cette route client

**Comment by naholyr** [comment]
La route client est `/people/(editor:582edfd9009b02561e8cd4b8)?organization=582edfcc009b02561e8cbce2`

Après vérification le `?organization` est assez compliqué à supprimer au final, trois solutions :

* Le supprimer mais ça nécessite quelques heures et une remise à plat de pas mal de choses au niveau des permissions et de ce qu'il est nécessaire d'avoir comme infos pour les connaître
* Lui affecter comme valeur une orga arbitraire parmi celles de l'utilisateur connecté
* Lui affecter comme valeur l'ID d'une orga "factice" mais existant réellement dans la base (mais ça nécessitera sûrement de mettre des filtres par ailleurs dans les API, a priori seulement dans le listing des orgas)

Pour le moment j'implémente la 2e solution histoire d'avoir un "quick win"

**Comment by naholyr** [comment]
Création de la #139 pour reprendre la suite plus tard
