### ISSUE TITLE
champs multiples simple genre nationalité

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#112]
enlever a forme ovale bordure et fond

**Comment by AdrienCossonSciencesPo** [comment]
Garde-t-on la croix juste à côté ? ou peut-on simplement supprimer une nationalité (par exemple) en l'effaçant ?

**Comment by paulgirard** [comment]
Faut tester les deux solutions auprès des users. Commence par ce qui te semble le mieux et on teste.

**Comment by paulgirard** [comment]
remplacer les croix encerclés par une mini poubelle
dans Organization.parentOrganizations (champs FK multiples) il y a un cercle vide bizarre et remplacer le crayon edit par le open_in_new
