### ISSUE TITLE
bug à la déconnexion 

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#118]
regarder dans la console l'erreur.
Par ailleurs la conséquence est que l'autocomplete sur le champs login ne marche pas

**Comment by t8g** [comment]
Non reproduit sur Chrome.

Peut-être un autre navigateur ?
Peut-être une séquence d'actions avant de se déconnecter ?

**Comment by Yomguithereal** [comment]
Je n'arrive pas à reproduire l'erreur dans la console. Par contre le problème d'autocomplete subsiste. Je vérifie sur Firefox de suite.

**Comment by t8g** [comment]
C'est quoi le pb d'autocomplete ? J'ai bien vu le ticket, mais c'est pas très clair pour moi.

**Comment by Yomguithereal** [comment]
En gros, si tu te connectes avec un compte, la prochaine fois que tu reviens au login plus tard, le browser a un auto-complete sur le form. Et ben quand tu te déco et que tu ne reload pas la page, on a plus l'auto-complete. Sur Firefox, le bug arrive une fois sur deux. Donc je pense qu'on va laisser tomber ça me semble être plus lié aux quirks des navigateurs qu'au code de l'appli.

**Comment by t8g** [comment]
Ok.
Ah oui c'est étrange l'autocomple qui se vire.

**Comment by Yomguithereal** [comment]
Dis-moi si tu penses que le code applicatif est en cause. Pour moi c'est le browser perso. Si tu crois aussi que c'est le browser, je clos l'issue.

**Comment by t8g** [comment]
Surtout j'ai aucune idée de pourquoi ça se produit ni de comment on peut agir là-dessus.
Donc +1 pour clore l'issue.
