### ISSUE TITLE
contrat

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#122]
- [ ] vérifier le modèle
- [ ] nettoyage
- [ ] mise à jour des enums
- [ ] importer d'après le readme

**Comment by LGAGELIN** [comment]
Nettoyage : il reste des valeurs FP7 dans  la colonne grants.organization, alors que FP7 devrait être dans grants.grantProgram et grants.organization UE ou Commission européenne. A voir avec Sophie

**Comment by LGAGELIN** [comment]
Nettoyage : ligne 106 du fichier, vérifier : 
- name du projet = Disattente de réponse et pratiques au nom de l'HOSPItalité-soCIéTés civiles européennes-Emotions,
- orga du PI = PACTE

**Comment by LGAGELIN** [comment]
Modèle : vérifier **activity.organizations.role** dans schema.activity.json. Il devrait y avoir une référence aux enums **activityOrganizationRoles**

**Comment by LGAGELIN** [comment]
Enums **activityPeopleRoles** : vérifier les rôles à distinguer sur les projets. A l'heure actuelle, on n'a que "PI" et "participant" dans les enums.
Dans le fichier Contrats, il y a confusion entre PI, coordinateur, responsable scientifique.

**Comment by LGAGELIN** [comment]
Modèle : vérifier **grants.overheadsCalculation** dans schema.activity.json. Pas de type ?

**Comment by Yomguithereal** [comment]
A priori c'est bouclé ça mais je souhaite une confirmation avant de clore.
