### ISSUE TITLE
LDAP resolution does not get now deactivated accounts

### ISSUE THREAD

**Issue by Yomguithereal** [SciencesPo/isari#125]
- [x] Improve matching
- [x] Find every needed person
- [ ] Mind the actif flag

**Comment by Yomguithereal** [comment]
Should match on name, firstName & email also. Beware of siactif for account creation thereafter.

**Comment by Yomguithereal** [comment]
Maybe use fuzzy search also.

**Comment by Yomguithereal** [comment]
Fuzzy search kills the server.

**Comment by LGAGELIN** [comment]
Resolution should be based on UID (prenom.nom) .
Not on Display name which is unsteady
