### ISSUE TITLE
Champs par dépendances nesté ?

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#128]
peut on faire un champs dépendant depuis un sous-objet vers une clef de l'objet supérieur ?

Je crois me souvenir avoir dit qu'on aurait pas le cas... oups.
faisable ou j'essaie de gérer ça avec le métier ?

```json
{
    "activityType": {
        "label": {
            "fr": "Type d'activité",
            "en": "Activity type"
        },
        "enum": "activityTypes"
    },
    "organizations": [
        {
            "role": {
                "label": {
                    "fr": "Rôle",
                    "en": "Role"
                },
                "enum": "activityOrganizationRoles:../../activityType"
            }
    ]
}
```

**Comment by naholyr** [comment]
Pas de souci c'est exactement le principe de la syntaxe mise en place. En revanche j'ai effectué pas mal de refacto autour des enums pour #101 (il y avait beaucoup de validations manquantes), il y aura peut-être encore un peu de boulot là-dessus donc je laisse l'issue ouverte pour un tour des enums nestés.

**Comment by paulgirard** [comment]
On a testé.
Il faut dans le cas cité ci-dessus il faut rajouter un .. pour sortir de la liste.

```json
"enum": "activityOrganizationRoles:../../../activityType"
```

Cette syntaxe passe côté client mais fait planter le serveur que ce soit à l'import ou au save.


```bash
/home/pgi/dev/isari/server/lib/enums.js:39
			return d.parent()
			         ^

TypeError: d.parent is not a function
    at targetPath.split.reduce (/home/pgi/dev/isari/server/lib/enums.js:39:13)
    at Array.reduce (native)
    at /home/pgi/dev/isari/server/lib/enums.js:35:44
    at EmbeddedDocument.validator (/home/pgi/dev/isari/server/lib/schemas.js:186:19)
    at /home/pgi/dev/isari/server/node_modules/mongoose/lib/schematype.js:742:28
    at Array.forEach (native)
    at SchemaString.SchemaType.doValidate (/home/pgi/dev/isari/server/node_modules/mongoose/lib/schematype.js:710:19)
    at /home/pgi/dev/isari/server/node_modules/mongoose/lib/document.js:1304:9
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by naholyr** [comment]
Après quelques tests il semble que la logique soit sauve et que je puisse généraliser le traitement. On peut laisser la partie client tel quel, et modifier le côté serveur, pour détailler :

* le premier "../" permet de remonter du champ "role" à l'objet le contenant (inutile côté serveur, on est déjà au niveau de l'objet), il semble assez "bizarre" mais je pense le laisser tel quel pour le moment vous éviter de multiples aller-retours dans les layouts
* le second "../" permet de remonter de l'objet à la liste (là encore inutile côté serveur où l'on remonte systématiquement à l'objet conteneur en zappant les couches "tableau")
* le troisième permet de remonter à l'objet racine qui nous intéresse

Concrètement, on a donc les cas suivants :

* le plus complet : ``{ champParent: …, items: [ { champEnum: "../../../champParent" } ] }`` → à traduire "../champParent" server-side
* sans liste : ``{ champParent: …, item: { champEnum: "../../champParent" } }`` → à traduire "../champParent" server-side (je dois encore tester à part ce cas qui ne se présente pas, donc a priori inutile)
* au même niveau : ``{ champParent: …, champEnum: "../champParent" }`` → à traduire "./champParent" server-side

Je peux donc m'en sortir en faisant des traductions de chemin selon le contexte.

**Comment by naholyr** [comment]
For review @Yomguithereal

**Comment by Yomguithereal** [comment]
Il faut juste gérer le `./` et c'est bon (note to self: mettre à jour les schémas ensuite).

**Comment by naholyr** [comment]
Done, to be reviewed

**Comment by Yomguithereal** [comment]
Je check.

**Comment by Yomguithereal** [comment]
C'est bon. Reviewed. Je clos.
