### ISSUE TITLE
création de champs vides de partout ! 

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#131]
Il faut qu'on éradique la création de champs vide dans les pipelines de données.
Ça crée des effets de bords pénibles.

Il faut vérifier que le client n'envoie pas de champs vide.
Il faut vérifier que mongoose ne renvoie pas de champs vide.
il faut vérifier que l'import ne crée pas de champs vide.

La validation devrait vérifier ça.

**Comment by naholyr** [comment]
Vérifier la piste "chaîne vide = supprimer le champ"

**Comment by naholyr** [comment]
Attention, maintenant la méthode `PUT` REMPLACE l'objet au lieu de le mettre à jour. Elle attend donc un objet complet et supprimera de la base les champs non définis. Cela correspond bien au comportement qu'on veut mettre en place pour la suite (cf. #134) donc normalement pas de soucis à craindre de ce côté. README mis à jour.
