### ISSUE TITLE
Remplacer la sauvegarde automatique par un bouton save + CRT-S

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#134]

**Comment by naholyr** [comment]
OK, avec deux points en suspens:

* Le bouton est un simple bouton posé en haut de formulaire, j'ai passé un moment à essayer de le rendre "sticky" mais aucune tentative n'a donné un résultat (testé: ng2-ui/ng2-sticky, makseo/ng2-sticky, md-fab-toolbar, les toasters et l'ajout de position:fixed qui semble ignoré).
* La compatibilité cross-platform des raccourcis clavier à vérifier, si ça ne marche pas quelque part voici la procédure la plus simple :
  * Ajouter un `console.log(pressed)` ici https://github.com/SciencesPo/isari/blob/e57bbba4b97c5d25712a3713cb6c018951b20009/client/src/app/utils.ts#L96 pour vérifier comment est reconnu le raccourci tapé
  * Ajouter le raccourci avec la bonne syntaxe dans la liste ici https://github.com/SciencesPo/isari/blob/e57bbba4b97c5d25712a3713cb6c018951b20009/client/src/app/data-editor/data-editor.component.ts#L19
