### ISSUE TITLE
Layout : autoriser des regroupements de champs multilignes

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#138]
Pour mieux maîtriser la disposition des formulaires il est nécessaire de pouvoir créer des regroupements de champs expandable avec label qui contiennent plusieurs lignes de fields.

```json
{
        "fields": [
           ["name","firstName"],
            "organizations",
          ["truc","bidule"]
        ],
        "label": {
            "fr": "organisation(s) impliquée(s)",
            "en": "related organization(s)"
        },
        "collapsabled": true
    },
```

Quelle difficulté ?

**Comment by t8g** [comment]
Fait
Mais question en suspens
Si on a 
[ field1, [ field2, field3 ], field4, field5 ]

Est-que que l'on doit faire

<table>
<tr><td colspan=2>field1</td></tr>
<tr><td>field2</td><td>field3</td></tr>
<tr><td colspan=2>field4</td></tr>
<tr><td colspan=2>field5</td></tr>
</table>

ou

<table>
<tr><td colspan=2>field1</td></tr>
<tr><td>field2</td><td>field3</td></tr>
<tr><td>field4</td><td>field5</td></tr>
</table>

Je suis parti sur l'option 1, qui me semble plus logique, mais elle suppose de réecrire les templates.

**Comment by paulgirard** [comment]
Oui la solution 1 est la plus logique.
Mais je n'ai pas compris pourquoi cela suppose de réécrire les templates ?

**Comment by paulgirard** [comment]
Ok oui il faut reprendre tous les layouts.
Such is life.
Pas de soucis c'est bien comme ça, je clos et met une issue pour reprendre les layouts
