### ISSUE TITLE
Duplication des formulaires d'éditions

### ISSUE THREAD

**Issue by naholyr** [SciencesPo/isari#140]
Scénario : j'arrive sur la liste (`/people?organization=…`), je clique sur une ligne pour entrer en mode édition (`/people/(editor:…)?organization=…). Puis je clique sur le bouton de création qui m'emmène alors sur `/people/(new//editor:…)?organization=…` au lieu de l'attendu `/people/new?organization=…`, ce qui fait que les formulaires sont dupliqués.

Ça n'a pas l'air d'avoir d'impact, les deux composants sont indépendants. Seulement `Ctrl+S` lance les deux sauvegardes simultanément.

On classe en bug ou en feature (d'un côté, ça donne un drôle d'affichage, de l'autre ça peut être pratique d'avoir une fiche "de référence" alors qu'on est en train d'en créer une autre) ?

**Comment by paulgirard** [comment]
On classe en bug.
Désolé.
Mais bel esprit, fallait tenter le coup de la feature ;)

**Comment by t8g** [comment]
Corrigé

**Comment by paulgirard** [comment]
mmm le bug est toujours présent pour moi en local ?
à débuguer ensemble ?

**Comment by t8g** [comment]
Ah oui zut
J'ai pas dû commité ce qu'il fallait

**Comment by t8g** [comment]
Mais quelle vacherie le router angular.
Bref c'est corrigé (pour de vrai cette fois)
