### ISSUE TITLE
titres/labels au sein des blocs OU bloc imbriqué ? 

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#141]
Imaginons un bloc "info perso"
Dedans nous souhaitons créer deux zones différentes "état civil" et "contact".
Soit on crée des sous-blocs, soit on ajoute des titres de sections (ce qui revient un peu au même non ?)

**Comment by paulgirard** [comment]
relates #138

**Comment by adriencossonscpo** [comment]
relates #176 pour reprise du layout
Nous avons opté pour les titres avec des blocs collapsable avec la possibilité d'imbriquer certains blocs entre eux.
