### ISSUE TITLE
ajouter un filtrage par dates des membres d'un labo (de People)

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#146]
Ajouter une requête qui sélectionne les membres qui ont une affiliation entre : 
- 1/01/2012
- 30/06/2017

Cette requête est utilisée par un bouton supplémentaire à côté de personnes en haut du tableau : "membres 2012-2016"

Il faut évaluer la possibilité de spécifier les dates début / fin de période dans le tableau.
Au moins faire en sorte de paramétrer la requêtes.

**Comment by Yomguithereal** [comment]
Correspond au brush de la viz.

**Comment by naholyr** [comment]
* labo = orga courante (scope)
* dates se chevauchent

**Comment by naholyr** [comment]
Cette requête a-t-elle un sens en mode "non filtré" ? Si oui comment doit-elle être interprétée ?

**Comment by naholyr** [comment]
cf. 7db8e1d

### Nouvelle option ``include=range``

* Réutilisation de l'option "include" puisque ce mode de filtrage est incompatible avec `include=externals` ou `include=members`
* Requiert les options `organization` (filtre), `start` et `end` (range de dates)

Exemple d'URL : ``/people?organization=584a8164650af36a7ac765c9&include=range&start=2012&end=2016``

Points à discuter :

* Si `academicMemberships.endDate` n'existe pas, le doc sera exclu des résultats
  * Doit-on ajouter un test du genre "si end = aujourd'hui, inclure les docs sans endDate" ?
* Je n'ai pas filtré sur `isariMonitored`, a priori on filtre déjà par ID d'organization donc on peut s'ouvrir le droit de faire cette requêtes pour des orgas non monitored

**Comment by paulgirard** [comment]
Les paramètres de query start et end doivent pouvoir être absent.

Le include include=members est un synonyme de include=range&start=today sans end.
Donc en faite j'aurai plutôt penché pour ajouter de paramètres start et end au include=members.

Un doc sans endDate doit être ajouté si il matche la période de temps genre si on requête : 
- start=2012 et end=2015 (les personnes qui ont été présentes entre ces deux dates)
Alors si on a un people qui a une affiliation start=2013 et pas de endDate, il doit être inclus.

Ok pour ne pas filtrer sur isariMonitored.

**Comment by naholyr** [comment]
* Je laisse les deux valeurs d'include distinctes puisque `members` implique le check sur `isariMonitored`, alors que `range` non, mais peut-être qu'il faut modifier ce comportement du coup ? En l'état `include=members` sur une organization avec `isariMonitored = false` ne retournera aucun résultat, alors qu'`include=range` pourra en retourner.
* J'inclus les users avec `endDate` non spécifiée, du coup pour ceux qui n'ont pas de `endDate` le seul test pertinent devient `startDate` ≤ *fin du range*, je ne vois pas de contre-exemple pour l'instant.

**Comment by naholyr** [comment]
For review @Yomguithereal

**Comment by Yomguithereal** [comment]
Ca a l'air de fonctionner mais je vais devoir essayer sur des applications concrètes.

**Comment by paulgirard** [comment]
Admettons que c'est bon comme ça je passe l'issue en design / ergonomie pour tester et ajouter les éléments front qui vont avec.
Il y a sans doute des problèmes avec les tests d'overlap de temps mais on débugguera ça avec des tests métiers.
