### ISSUE TITLE
changement d'icône du menu

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#149]
Icône du menu:
icône organisation : https://material.io/icons/#ic_account_balance
icône activités : https://material.io/icons/#ic_apps

Ajouter des tolltips aux icônes

ajouter le nickname du user courant à la place de account

**Comment by AdrienCossonSciencesPo** [comment]
Il ne reste plus qu'à ajouter le tooltip pour chaque icône. D'ailleurs, dois-je le mettre sur le bouton d'export HCERES et le changement de langue ?
