### ISSUE TITLE
isolation des CVs en écriture 

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#156]
Un research member peut écrire le CV d'un autre membre de son labo.
C'est un problème.
Un research membre doit pouoir lire mais ne pas éditer un  CV d'un autre membre

**Comment by naholyr** [comment]
Quel est le user concerné ?

Aujourd'hui l'algo est celui-ci :

* Moi-même → lecture+écriture
* Central reader → lecture seule
* Central admin → lecture+écriture
* Center editor ou Center admin d'une des organizations du champ `academicMemberships` du people → lecture+écriture (j'ai vérifié cette partie je n'ai pas trouvé de bugs, j'ajouterai les tests pour le valider)
* External → lecture+écriture
* Autres cas → lecture seule

La condition "external" est la suivante :

* **aucun** des `academicMemberships` n'a une `endDate` spécifiée, dans le futur, et une organization isariMonitored

Les algos sont-ils corrects ?

**Comment by paulgirard** [comment]
Le cas qui pose problème est le suivant.
Je suis connecté en tant que center_member.
Je peux éditer les pages people des autres center_member de mon centre alors que je ne devrais pouvoir éditer que la mienne.

Pour tester, se connecter avec tommaso.venturini et éditer barbara.bender fonctionne.

**Comment by naholyr** [comment]
Il y avait une erreur dans la définition d'"external", une endDate *non spécifiée* le disqualifiait alors que ça devait être l'inverse. C'est corrigé.
