### ISSUE TITLE
validation à la création d'objet

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#157]
Le scénario de l'ajout serait le suivant : 
   
- le click sur ajouter fait apparaître un modal
- ce modal est construit comme suit:
    - "Avant de créer un objet merci de vérifier si cet {objet} n'est pas déjà présent :"    
    - demande le nom de l'objet à créer dans un input
    - recherche d'objet dans elasticsearch (même endpoint que l'autocompletion des FK)
    - présentation des résultats avec icône afficher dans un nouvel onlget
    - un bouton "créer un nouveau {objet}" qui n'apparaît que si une recherche a été faite

Quand on clique on passe à la création.

**Comment by LGAGELIN** [comment]
Exemple de fenêtres modales :

Si trouvé :
![image](https://cloud.githubusercontent.com/assets/22589536/21936821/e313c4f2-d9b2-11e6-8de0-d6abd16dec08.png)

Si rien trouvé :
![image](https://cloud.githubusercontent.com/assets/22589536/21936849/fdafe764-d9b2-11e6-8bf8-86afc3c95b21.png)

**Comment by t8g** [comment]
Pushé
À tester

**Comment by paulgirard** [comment]
Ajouter le style graphique de l'application : 
- police de texte de l'application
- couleur rouge et non violet du champs et du bouton
- passage par l'i18n
- change la phrase en "Pour ajouter des Personnes|Activités|Organisations, merci de vérifier d'abord si elles n'existent pas déjà."

**Comment by t8g** [comment]
Fait
