### ISSUE TITLE
Pré-filtrer les Activity par type d'activité

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#164]
A l'heure actuelle, les Activities sont visibles sur un même tableau, tous types confondus.  Pour les utilisateurs, il n'est pas intuitif de choisir le type d'activité, car il faut aller saisir son type dans la colonne. Cela suppose de connaître l'application. Il faudrait proposer un menu avec des pré-filtres.
Serait-il possible de mettre en place plusieurs boutons à droite du titre Activités (comme pour Personnes) permettant de filtrer : Invités, Projets de recherche, Doctorats, Séjours à l'étranger ?

**Comment by paulgirard** [comment]
duplicates #243
