### ISSUE TITLE
amélioration Champs de type Date

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#166]
A l'usage, on remarque qu'il est "confusing" pour l'utilisateur de sélectionner les informations dans un champ Date. Il faudrait légender les zones permettant de choisir le jour, mois et l'année, représentés aujourd'hui par "_".

De plus, on ne peut pas annuler la saisie. Est-il possible d'ajouter une X pour annuler.

**Comment by paulgirard** [comment]
On garde le comportement actuel pour les icônes.

En revanch, le champs est éditable en mode texte libre malgré le widget ce qui permet de mettre une valeur arbitraire dans le champs.

Ce serait idéal de permettre d'éditer le champs en mode texte mais cela demande une validation.
Pour le moment empêcher l'édition en mode texte.
Seul le click doit déclencher le widget et seul le widget peut écrire dans le champs

**Comment by paulgirard** [comment]
- [ ] enlève l'icône x du bas
- [ ] enlève l'icône poubelle
- [ ] on ajoute une petite icône x au blocs jour / mois et année en haut du module (comportement de l'icône poubelle + effacement en cascade pour l'année (qui n'était pas possible avant).
- [ ] enlève l'icône flèche ronde de gauche "annuler"
- [ ] récupérer le comportement de l'icône flèche ronde pour les actions ECHAP et BLUR
- [ ] ajouter un handler sur la touche entrée pour actionner "valider"

**Comment by adriencossonscpo** [comment]
Pour le moment, le Blur fonctionne uniquement après avoir cliqué sur le champ date, sans avoir modifié l'un des éléments de date.

**Comment by Yomguithereal** [comment]
Je viens de commenter le `@HostListener` parce que le fait de l'instancier sur tous les composants dates rend l'intégralité du formulaire inutilisable a cause du lag. Il faut trouver un meilleur moyen de capturer les events que d'écouter window.

**Comment by adriencossonscpo** [comment]
En reprenant la méthode utilisée pour naviguer dans les select et multi-select, il suffirait de déclarer les touches comme suit : "const ESC = 27;" et d'écrire une fonction onKey($event).
Cela fonctionne bien avec la touche Escape, mais pas Entrée.
