### ISSUE TITLE
Login bug with ldapUid & no isariAuthorizedCenter

### ISSUE THREAD

**Issue by Yomguithereal** [SciencesPo/isari#168]
Si quelqu'un se connecte et a un ldapUid présent dans la base mais pas de isariAuthorizedCenter, on arrive sur une page vide et un bug dans la console concernant des global orgs.

**Comment by naholyr** [comment]
Faudrait-il qu'il n'ait pas le droit de se connecter dans se cas ? Ou plutôt un message "propre" sur la home ?

**Comment by Yomguithereal** [comment]
Cette personne ne devrait pas avoir le droit de se connecter. @paulgirard tu peux confirmer?

**Comment by Yomguithereal** [comment]
@paulgirard confirme. Plus tard dans le futur il faudrait sinon prévoir de ne lui afficher que sa fiche en lecture seule mais c'est le turfu.

**Comment by paulgirard** [comment]
Je confirme on doit renvoyer sur la home avec le message lié aux erreurs 403

**Comment by naholyr** [comment]
Done, ping for review
