### ISSUE TITLE
Feature: Custom columns

### ISSUE THREAD

**Issue by Yomguithereal** [SciencesPo/isari#169]
Nouvelle feature: pour pouvoir ajouter les colonnes complexes du genre agrégation, résumé de colonnes nestées profondes etc.

En gros, on parle de colonnes custom liées à des templates qui sont de simples reducers prenant en entrée un document et potentiellement plus tard un context (indexes, whatever...):

```
function numberOfAffiliationsColumn(doc) {
  return doc.academicMemberships.length;
}
```

Les cas d'usage évoqués sont des sommes de chiffre ou un récapitulatif de champs nestés profonds (genre les grants des activités).

**Comment by naholyr** [comment]
Traitée par la PR #182
