### ISSUE TITLE
Dans le tableau People, colonne Activités Personnelles, la clé de l'enum s'affiche au lieu de la valeur

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#170]
Dans la colonne "Activités Personnelles" du tableau People , c'est la clé de l'enum type d'activité qui apparaît au lieu de la valeur (collaborationsscientifiques, editorial, etc...)
Exemple : fiche de Laurent Lesnard (CDSP)

**Comment by naholyr** [comment]
Ajout d'une API dédiée pour simplifier ce traitement, l'objectif étant de retourner un objet ``{ label: { [lang]: '…' } }`` mais ça devient pénible s'il faut gérer les différents cas de traduction selon les enums. L'API est donc ``formatEnum(nomDeLEnum, valeurDuChamp, fonctionDePersonalisationDesLabels)``

* Le nom de l'énum est celui dans `enums.json`, par exemple *personalActivityTypes*
* La valeur du champ est… la valeur du champ, par exemple *a.personalActivityType*
* La fonction de personnalisation permet de customiser chaque label, elle sera appelé avec *(valeur du label, langue)*, par exemple ``label => label + ' ' + a.startDate + '-' + a.endDate``

**Comment by naholyr** [comment]
Done, ready for review
