### ISSUE TITLE
Dans le tableau People, le code nationalité s'affiche au lieu du libellé

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#172]
Dans le tableau People, au niveau de la colonne Nationalités, les codes ISO des nationalités s'affichent.
Il faudrait que cela soit le libellé (française, arménienne, etc...) comme dans le formulaire.

**Comment by naholyr** [comment]
On avait parlé de la possibilité de gérer les enums dans le module templates, en réalité ce n'est normalement pas nécessaire et il s'agit bien d'un bug.
Les enums sont censés être gérés automatiquement, mais on a perdu les countries, currencies et languages en cours de route.

**Comment by naholyr** [comment]
Done, ready for review
