### ISSUE TITLE
refacto des templates : colonne custom + gestion des enums

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#177]
Il y a trois issues qui demandent un travail de fond sur les templates + columns
Il faut qu'on décrive le comportement souhaite pour résoudre #170 #172 #169

**Comment by naholyr** [comment]
Concrètement c'est un objet ``{ label: { fr: …, en: … } }`` par souci de cohérence avec les enums et autres structures du même accabit

**Comment by naholyr** [comment]
3 issues, 3 réponses :
- colonnes virtuelles pour #169 
- géré automatiquement pour #172 (c'était un bug)
- géré par un helper pour #170 

closed as duplicate

**Comment by LGAGELIN** [comment]
Je rouvre l'issue car la recherche dans le Tableau sur les colonnes Nationalités et Activités Personnelles ne fonctionne plus.

**Comment by paulgirard** [comment]
j'ouvre une nouvelle issue
