### ISSUE TITLE
format des champs imbriqués dans l'enums

### ISSUE THREAD

**Issue by naholyr** [SciencesPo/isari#18]

**Comment by naholyr** [comment]
La proposition consiste à abandonner la syntaxe `KEYS(*)` pour le champ de base, ça devient un enum standard, pas de raison d'avoir une spécificité de ce côté.
Pour le sous-champ en revanche on garde la syntaxe `enum.$champ` (ou autre à définir, selon les besoins du client par @t8g) et un format objet pour l'enum (valeurs factices déjà posées dans `enums.json`).

**Comment by naholyr** [comment]
Vu avec @paulgirard on met de côté pour réfléchir au modèle, quote myself :

> cela dit en essayant de l'exprimer technique c'est déjà tellement complexe que je me demande s'il y a pas un souci de modélisation
> ce qui est compliqué c'est qu'il faut indiquer une relation, ici indiquer que l'enum de `activity.people[i].role` dépend de la valeur de `people[_id = activity.people[i]._id].personalActivities[`**???**`].personalActivitySubType`
> je sais pas comment exprimer le "???"

**Comment by naholyr** [comment]
On partira plutôt sur un système façon "templates", avec des fonctions exportées

**Comment by paulgirard** [comment]
Reste à définir le format de ce fichier fonction de validation des champs imbriqué.
Je compléterai quand la structure sera en place

**Comment by naholyr** [comment]
## Fonctionnement des enums dépendants

### Schéma

On préfixe le nom de l'énum "spécial" par ``special/`` :

* ``{ "enum": "special/enumName" }`` ou ``{ "softenum": "special/enumName" }``

### Implémentation

Dans ``specs/enums.special.js``, on doit implémenter la méthode ``enumName`` :

```js
exports.enumName = (object, field, objectId, fieldPath) => {
  // Retourner la liste (ou la promesse de la liste) des valeurs
  // false, null, etc. seront convertis en liste vide
}

// Indiquer le nom du modèle Mongoose correspondant, pour permettre la conversion id → object
exports.enumName.modelName = 'ModelName'
```

#### Format du retour

Enum classique :

```js
[
  {
    "value": "valeur de la suggestion",
    "label": {
      "fr": "descriptoin de la suggestion",
      "en": "suggestion's description"
    }
  },
  …
]
```

### API REST

Les enums "spéciaux" sont servis par l'URL correspondante dans l'API :

* ``/enums/special/enumName?id=objectId&path=fieldPath``

Par exemple : http://isari/enums/special/personalActivitySubtype?id=58137043cc400e1339af3bcc&path=personalActivities.1.personalActivitySubtype sera invoquée lorsqu'on entre dans l'édition du champ "personalActivitySubtype" du second bloc des "personalActivities" du people correspondant.

**Comment by naholyr** [comment]
Exemple de déroulement détaillé :

* Le schéma indique ``{ "Model": { "toto": [ { "tata": { "enum": "special/bidule", … }, … } ], … }, … }``
* Le front appelle ``/enums/special/bidule?id=objectId&path=toto.0.tata``
* Le back récupère *specs/enums.special.js*``.bidule`` qui exporte une méthode *``key``*, qui retourne ``"machin"``
* Il va chercher dans *specs/enums.json*``.bidule.machin``, qui contient une liste de suggestions qui sont retournées au front

**Comment by paulgirard** [comment]
Et on ne pourrait pas mettre la.logique du enum.special.js côté client
plutôt que de passer par l'api ?

Je.me réveille tard sur ce point.
Au pire on mettra ça dans un futur projet de refactoring.

Pour le moment faisons rapide.

Le 15 nov. 2016 9:05 AM, "Nicolas Chambrier" <notifications@github.com> a
écrit :

**Comment by t8g** [comment]
On va être obligé de passer la logique côté client oui

On a vu un cas avec avec @naholyr qui ne marche pas avec la soluce en l'état

Si j'ai mis un activityType, mais que la sauvegarde ne s'est pas lancé (manque champ obligatoire ailleurs) et que l'on veut choisir un ActivitySubType, le serveur ne voit rien dans le champ activityType et donc ne retourne aucune proposition.

Pire si on a modifié le activityType et que la sauvegarde ne s'est pas lancée, on a des propositions sans rapport (en rapport avec l'ancienne valeur de activityType).

Bref ... pas glop.

**Comment by paulgirard** [comment]
Ok ça confirme mon pressentiment.
Du coup pas le choix faut passer la logique côté client...

**Comment by paulgirard** [comment]
Je clos.
Je ferais des rapports de bug dans debug
