### ISSUE TITLE
Ajouter un field type =  'Float' pour permettre au client d'incrémenter par pas de 0.1 

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#180]
Les flèches d'incrémentation perturbent la saisie du champ **taux d'occupation** dans **People.**
Si un montant avec une décimale est renseigné, l'incrémentation par la flèche supprime les décimales.

Il faut soit permettre l'incrémentation par décimales, soit supprimer la possibilité d'incrémenter via les flèches.

**Comment by paulgirard** [comment]
Je renomme l'issue.
Un workaround temporaire possible est de transformer les champs ETP en string.

**Comment by Yomguithereal** [comment]
On peut aussi ajouter a l'input les valeurs min & max et utiliser l'attribut step.
