### ISSUE TITLE
menu de la page "mon profil"

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#183]
En l'état on ne peut plus revenir au menu classique.
Il faut réfléchir à une solution.
Le plus simple est d'ajouter un click sur le logo ISARI pour revenir à la racine.

**Comment by adriencossonscpo** [comment]
On peut également ajouter une icône du genre 'porte de sortie' avec le lien de redirection. Reste a savoir exactement si on veut revenir au panneau d'affichage des différents centres auxquels l'utilisateur est affecté (ce que fait déjà le logo SciencesPo quand on clique dessus) ou à la page des people du centre sur lequel on était).

**Comment by LGAGELIN** [comment]
Autre solution (ma préférée): cliquer sur Mon Profil ouvre la fiche de la Personne dans un autre Onglet (onglet nommé comme les autres). Comme ça on ne perd rien du tout.
