### ISSUE TITLE
Nationalités : la liste des codes ISO apparaît aussi

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#191]
Dans le champ Nationalités, lorsqu'on saisit des caractères, la liste de valeurs fait apparaître  des codes ISO. Il ne devrait y avoir que les libellés des nationalités.
![image](https://cloud.githubusercontent.com/assets/22589536/21609957/8833ffce-d1c5-11e6-9fbc-0bdce5782dcb.png)

**Comment by Yomguithereal** [comment]
La raison pour laquelle on a ces codes ISO est que nous n'avons pas de label en français ni en anglais pour elle dans notre enum countries.

**Comment by LGAGELIN** [comment]
C'est correct maintenant, on ne voit plus les codes ISO

**Comment by LGAGELIN** [comment]
Mise à jour enum.countries.json sur la branche DEV : harmonisation lowercase pour 3 nationalités + suppression d'un doublon ("chinoise")
