### ISSUE TITLE
Edition de champs multi-valués : impossible d'ajouter de nouvelles valeurs

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#196]
Sur des champs multi-valués type Nationalités, Méthodes, si une valeur est déjà renseignée lorsqu'on consulte la fiche People, il est impossible d'ajouter une deuxième valeur. On n'a aucun indicateur pour savoir où cliquer pour ajouter une valeur.
La seule possibilité est de supprimer la valeur actuelle puis d'ajouter les valeurs.

A traiter avec l'issue #82

**Comment by adriencossonscpo** [comment]
relates #82

**Comment by paulgirard** [comment]
duplicates de #230
