### ISSUE TITLE
Bug Layout : Affichage des champs multilignes après clic "Ajouter"

### ISSUE THREAD

**Issue by adriencossonscpo** [SciencesPo/isari#197]
Le bug se situe en partie ici : 
layout.people.grades.json
On aimerais mettre les startDate & endDate sur la même ligne. Le problème arrive au moment d'ajouter un grade via le bouton "Ajouter". En effet, on ne voit plus que la startDate, et une partie du "md-menu" de la date avec les boutons undo, clear et done en hardcode.
Après avoir cliqué sur "Ajouter", aucune autre action est possible.

**Comment by adriencossonscpo** [comment]
Le problème est bien plus général que cela.
Il surgit lorsqu'on clique sur le bouton Ajouter où apparait deux champs alignés, quels qu'ils soient.

**Comment by t8g** [comment]
Ouf, fait
