### ISSUE TITLE
authentification (API et Front) CAS ou LDAP ?

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#20]
process d'authentification : 
- si un user load isari avec pas de session ou session expiré : 
  - on l'envoie vers http://isari.sciences-po.fr/login
  - cette page et un formulaire login/mot de passe
  - au submit le serveur doit faire une requête LDAP
  - requête LDAP (on peut mettre un paramètre de conf dev pour bypasser le LDAP)
       HOST de dev : ldapdevl.sciences-po.fr (nécessite une connexion VPN)
       DN: ou=Users,o=sciences-po,c=fr
       vérfiication du flag: scpoactifsi = 1;
  - la requête répond succès ou échec

Si échec, retour au login avec un message de type "vous vous êtes trompé"

Si succès c'est le login du formulaire qui indique le people concerné car il est censé matcher le champs LdapUid de la collection people

Si on ne trouve pas le people il faut renvoyer un unauthorized 401. On designera une jolie page Forbidden.

On redirige vers la home et c'est le champs ISARIAuthoriedCenter et ISARIRole qui permet de construire la home en fonction du profile de l'utilisateur.

Si le champs ISARIAuthoriedCenter est vide, on lui montre que le CV en lecture

**Comment by naholyr** [comment]
L'authentification est implémentée côté serveur, pour tester il faut :

## 1. Configurer

cf. `config/default.toml`, a priori la seule chose à modifier serait l'URL, j'ai mis une valeur arbitraire logique :

```toml
[ldap]
url = 'ldap://ldap.sciences-po.fr'
dn = 'ou=Users,o=sciences-po,c=fr'
activeFlag = 'scpoActifSI'
```

## 2. Tester

### En ligne de commande

J'ai laissé trainer un script (**temporaire**) utilisable en CLI pour tester l'authentification, usage : `node test-ldap <login> <password>`. Attention de bien spécifier la variable d'environnement **``NODE_ENV=production``** de votre côté si vous voulez tester avec le LDAP de prod. Exemple en dév :

![selection_403](https://cloud.githubusercontent.com/assets/214067/19763336/dbb242f4-9c3d-11e6-9c95-00090f635601.png)

A priori ce script n'a pas vocation à survivre à cette issue.

### Dans un navigateur

J'ai ajouté une URL (**temporaire**) accessible sur ``/login`` quand le serveur est lancé. Pour se connecter à la production ça donnerait :

* ``npm start``
* Ouvrir http://localhost:8080/login
* Vérifier le processus (les requêtes sont faites en Ajax sur ``/auth/login``, ``/auth/logout`` et ``/auth/myself``)

A priori cette page n'a pas vocation à survivre à cette issue. Elle sera remplacée par une page ng2.

**Comment by naholyr** [comment]
## Authentification "magique"

Pour désactiver LDAP (environnement de dév sans VPN, offline, autre…) il suffit de créer/modifier le fichier `server/config/local.toml` et d'y ajouter :

```toml
[ldap]
skip = true
```

À partir de là, aucune connexion à LDAP n'est faite, et les mots de passe sont automatiquement acceptés sans vérification.

**Comment by naholyr** [comment]
La partie authentification côté serveur est a priori terminée, le reste consiste à appliquer les permissions au niveau objet puis champ, objet d'une autre issue : #34.

Concernant cette issue, la formulaire de login et la home sont les dernières étapes.

**Comment by paulgirard** [comment]
le formulaire a été fait. je clos
