### ISSUE TITLE
Import DS Academic des PRAG : dates de fin de rattachement au labo et au département incorrectes

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#200]
A l'heure actuelle, les PRAG visibles dans ISARI sont ceux rattachés au labo CHSP et au départment d'histoire. 
Exemples : Marie SCOT, Albert KECHICHIAN, Pierre GROSSER, etc...

Il est correct de les rattacher au labo CHSP et au département d'histoire. La date de début de rattachement est correcte dans les 2 cas (labo et département). En revanche, il y a une date de fin renseignée, ce qui est incorrect. Il faut laisser la date de fin à vide car on ne connaît pas leur date de départ (et ils sont toujours membres de ce labo et du département).
Même problème dans le Parcours : un contrat MESR a été rattaché pour la période où ils sont PRAG avec tutelle MESR, mais il faut laisser la date de fin vide. A l'heure actuelle elle est renseignée comme celles du département et du labo.

**Comment by Yomguithereal** [comment]
C'est donc qu'on a des erreurs dans les data de DS_Academic et cela doit y être corrigé à cet endroit plutôt que de déployer des heuristiques hasardeuses. Sophie s'est désignée volontaire pour cette mission.
