### ISSUE TITLE
ajouter des choix de deux dates de filtrage dans les tableaux PEOPLE et ACTIVITY

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#205]
En haut du tableau à côté du sélecteur de filtrage custom on ajoute deux champs dates ou un widget timerange pour sélectionner une date de début et une date de fin de période.

Ces deux dates permettent de restreindre le filtrage du tableau par date en refaisant une requête à l''API #146

**Comment by paulgirard** [comment]
raaa pas de range dans ng2 material que un slider https://github.com/angular/material2/blob/master/src/lib/slider/README.md

**Comment by Yomguithereal** [comment]
C'est ajouté par contre c'est la query de date qui semble fishy.

**Comment by LGAGELIN** [comment]
Déjà vu avec Paul , je confirme que la recherche par date est OK dans People, mais pas dans Activity

**Comment by paulgirard** [comment]
Mes tests hier sur activity ne m'ont pas faire trouver de problèmes avec le filtrage par date.
Peux tu préciser ce qui ne marche pas?

**Comment by LGAGELIN** [comment]
Sur Sciences Po, Séjours à l'étranger, Date début = 18 sept 2014

![image](https://cloud.githubusercontent.com/assets/22589536/22589503/e825b406-ea0a-11e6-81cf-71c75017e6b0.png)

**Comment by paulgirard** [comment]
je clos pour ouvrir un ticket par bug
