### ISSUE TITLE
Cache angular et rôles

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#207]
Sous Chrome, connectée en tant que sophie.jacquot, puis en tant que chercheur nicolas.delalande, on peut voir les titres des blocs Tenure Track, Primes, qui sont confidentiels et ne doivent pas être visibles par le Nicolas Delalande, qui est un People sans rôle.
En rechargeant la page via ctrl R, les blocs confidentiels disparaissent.
Puis en se reconnectant en tant que Sophie Jacquot, les champs confidentiels réapparaissent à nouveau. 

En synthèse, on a le problème de cache que lorsque le rôle d'accès diminue.

**Comment by t8g** [comment]
Done
