### ISSUE TITLE
Export Tableau HCERES - onglet 3.4 post-doc & ch-invités

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#212]
Liste des postdocs et invités depuis le 1/01/2012

**Filtre des postdocs :**
grade= “postdoc” et endDate du grade > 1/01/2012 ou endDate vide et une academicMembership sur le labo.
Les 2 périodes se recouvrent. La date de fin du recouvrement doit être > à 01/01/2012

**Filtre des Invités :**
On check les Activity “mob_entrante” ayant en orga avec le rôle “orgadaccueil” le labo concerné
Sur une période qui déborde après le 1/01/2012

**Infos à afficher :**
Nom
Prénom
genre
date de naissance
date d’arrivée :  
- pour les postDoc =Date d’entrée dans le grade “postdoc”
- pour les inités = date de début de l'activité d'invitation Activity “mob_entrante” 
date de départ de l’unité = date de départ de l’invité, ou date de fin du grade “postdoc”

mettre à jour les deux totaux en bas du tableau.

**Comment by paulgirard** [comment]
Done.
On ne pourra pas ajouter les cellules totaux trop compliqué à faire pour nous et très simple à faire à la main avec une formule dans excel.

**Comment by LGAGELIN** [comment]
Pouvez-vous me confirmer ce qui a été implémenté concernant cet export des Invités :
y a-t-il un test sur Activity de type mob_entrante ou seulement sur les People ayant une affiliation Invité sur le labo sur la période HCERES ?
