### ISSUE TITLE
Export Annexe 4 HCERES - 1. Activités éditoriales

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#214]
Les infos à afficher sont :
people.name people.firstName, personalActivities.description, startDate-endDate (si la endDate est vide et que startDate est non vide, afficher "depuis [startDate]”)

**Participation à des comités éditoriaux (revues, collections)**

Filtre :
personalActivityType = “editorial”
ET 
personalActivitySubtype = vide  OU personalActivitySubtype = “revueScientifique” OU [personalActivitySubtype=“collectionScientifique” + role= “membre”]

**Direction de collections et de séries**

Filtre : 
personalActivityType = “editorial”

ET 
[personalActivitySubtype = “collectionScientifique” ET role = direction ou codirection ou presidence]

**Comment by Yomguithereal** [comment]
J'ai un premier jet pour ça.

**Comment by Yomguithereal** [comment]
Il reste notamment à définir comment on accède à ceci depuis l'interface.
