### ISSUE TITLE
Export Annexe 4 HCERES - 2. Activités d'évaluation

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#215]
Pour chacune des listes ci-après, les infos à afficher sont :
people.name people.firstName, personalActivities.description, startDate - endDate (si la endDate est vide et que startDate est non vide, afficher "depuis [startDate]”)

**Responsabilités au sein d’instances d’évaluation**
Filtre:
personalActivityType = “évaluations”
 personalActivitySubType= “responsinstanceevaluation” ou = “communauteprogrammation" ou = “evaluationpairs”

**Évaluation d’articles et d’ouvrages scientifiques**
filtre : 
personalActivityType = “editorial” && personalActivity.role =“reviewer”

**Évaluation de laboratoires (type Hceres)**
Filtre :
personalactivityType = “évaluations”  && personalactivitySubType = “evaluationstructure”

**Évaluation de projets de recherche**
Filtre :
personalactivityType = “évaluations” && personalactivitySubType = “evaluationprojets”

**Comment by Yomguithereal** [comment]
A priori c'est bouclé.
