### ISSUE TITLE
Export Annexe 4 HCERES - 3. Activités d'expertise scientifique

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#217]
Pour chacune des listes ci-après, les infos à afficher sont :
people.name people.firstName, personalActivities.description, startDate - endDate (si la endDate est vide et que startDate est non vide, afficher "depuis [startDate]”)

**Activités de consultant**
Filtre :
personalactivityType = “expertise” && personalactivitySubType = “consultance”

**Participation à des instances d’expertises (type Anses) ou de normalisation**
Filtre :
personalactivityType = “expertise” && personalactivitySubType = “instance”

**Expertise juridique**
Filtre :
personalactivityType = “expertise” && personalactivitySubtype = “juridique”

**Autres expertise (Sciences Po)**
Filtre
personalactivityType = “expertise”  && personalactivitySubtype= vide ou = “audition” ou =”rapport”

**Comment by Yomguithereal** [comment]
A priori c'est fait.
