### ISSUE TITLE
Export Annexe 4 HCERES - 5.	Post-doctorants et chercheurs accueillis

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#218]
Il s'agit de présenter 2 listes postdoc et chercheurs invités.

**Post-doctorants :** 
Filtre : tester le grade académique postdoc pendant la période d’appartenance au labo
Affichage :  people.name people.firstName, startDate - endDate (si la endDate est vide et que startDate est non vide, afficher "depuis [startDate]”)

**Chercheurs accueillis :**
Filtre : tester les invités arrivés entre le 1/01/2012 et le 30/06/2017 ou arrivés avant et partis pendant la période.
Infos à afficher :
people.name people.firstName, orga d’origine, pays de l’orga d’origine, activity.startDate - activity.endDate

**Comment by Yomguithereal** [comment]
Normalement c'est bon pour celle-ci.
