### ISSUE TITLE
Export Annexe 4 HCERES - 7. Contrats de recherche financés par des institutions publiques ou caritatives

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#219]
**Infos à afficher :**

- acronyme (si existant) (activity.acronym)
- intitulé du projet (si non vide)   (activity.name)
- organisation financeur (activity.grants.Organization)
- programme de financement (activity.grants.grantProgram)
- instrument de financement (activity.grants.grantInstrument)
- prénom et nom du Responsable Scientifique du projet  OU du Principal Investigator si pas de responsable scientifique
- rôle du labo sur l'activité (coordinateur ou partenaire)

**Premier filtre à appliquer** : activity.activityType = "projetderecherche"

**Contrats européens (ERC, H2020, etc.) et internationaux (NSF, JSPS, NIH, Banque mondiale, FAO , etc.)**
Filtres :
 Type de financement = international individuel OU international collaboratif

**Contrats nationaux (ANR, PHRC, FUI, INCA, etc.)**
Filtres : Type de financement = national individuel OU national collaboratif

**Contrats avec les collectivités territoriales**
Filtres : Type de financement = territorial individuel OU territorial collaboratif

**Contrats financés dans le cadre du PIA**
Filtres : Programme de financement = PIA

**Contrats financés par des associations caritatives et des fondations (ARC, FMR, etc.)**
rien

** Autres à trier **

Tous les grants qui n'ont pas d'enum grantTypes ou ont un enum différent de : 
collaboratifinternational
individuelinternational
collaboratifnational
individuelnational
interne
collaboratifterritorial
individuelterritorial

**Comment by Yomguithereal** [comment]
Bon ça a priori c'est bon aussi mais il faudra terminer les requêtes et probablement ajouter des dates au template.

**Comment by LGAGELIN** [comment]
ça a l'air d'être correct sauf pour le grant instrument, qui  ne semble pas récupéré correctement.

On trouve des codes enums à la place du libellé.

![image](https://cloud.githubusercontent.com/assets/22589536/22149523/8f0c9f7a-df14-11e6-9599-194c78be9420.png)
