### ISSUE TITLE
ajouter le user id dans l'editlog

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#22]
le user id a stocké dans l'editlog est le LdapUid.
On pourrait mettre le mongoUID aussi.

**Comment by naholyr** [comment]
Le `ldapUid` est d'ores et déjà ajouté (req.session.login). Pour le mongoId je ne suis pas sûr que ça soit pertinent vu qu'on a déjà un ID unique, à moins que le ldapUid soit amené à changé ?

**Comment by Yomguithereal** [comment]
@paulgirard ping.

**Comment by paulgirard** [comment]
si ça ne nous coûte pas trop de temps je mettrai bien le mongoID au cas où.
J'ai une confiance limitée au LDAPUID surtout qu'ils vont dépkoyer une nouvelle version

**Comment by paulgirard** [comment]
si ça ne nous coûte pas trop de temps je mettrai bien le mongoID au cas où.
J'ai une confiance limitée au LDAPUID surtout qu'ils vont dépkoyer une nouvelle version

**Comment by Yomguithereal** [comment]
Je vais rajouter ça.

**Comment by Yomguithereal** [comment]
Pas si trivial parce que cela implique de multiplexer le `latestChangeBy` des modèles.

**Comment by paulgirard** [comment]
dans ce cas on oublie.
