### ISSUE TITLE
Export Annexe 4 HCERES - 8. Indices de reconnaissance

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#220]
A implémenter si on est capable de distinguer un Prix d'une Distinction

**Comment by LGAGELIN** [comment]
On veut présenter les Prix et Distinctions des **People** et des **Activités** obtenus pendant la période HCERES (1/01/2012 au 30/06/2017) . Les informations seront affichées dans paragraphes suivants :

- Prix
- Distinctions
- Responsabilités dans des sociétés savantes
- Invitations à des colloques / congrès à l’étranger, séjours dans des laboratoires étrangers

Les 2 derniers paragraphes ne concernent que les People. Les autres concernent les People et les Activity.

**Infos à afficher pour les People:**
people.name, people.firstName, personalActivities.description, startDate, endDate (si la endDate est vide et que startDate est non vide, afficher "depuis [startDate]”)

**Infos à afficher pour les Activités :**

**Prix** :
filtre People = People.Distinctions.distinctionType = "prix"
filtre Activité : 

**Distinctions** :
Filtre People =People.Distinctions.distinctionType ="distinction"
Filtre Activité : 

**Responsabilités dans des sociétés savantes**
Filtre People uniquement : = Activités et responsabilités > type d’activité = collaborations scientifiques + rôle = direction, co-direction, présidence

**Invitations à des colloques / congrès à l’étranger, séjours dans des laboratoires étrangers**
Filtre People uniquement = tous les séjours à l’étranger

**Comment by Yomguithereal** [comment]
Les prix et distinctions sont une seule et même chose (décision @paulgirard et Sophie hier) du coup je merge les catégories.

**Comment by Yomguithereal** [comment]
A priori c'est bon.

**Comment by LGAGELIN** [comment]
Pour remonter l'activité personnelle dans l'annexe 4 8-Indices de reconnaisances, il faut checker l'academicMembership de la personne sur le labo concerné sur la période. Sinon, on se retrouve avec une activité d'une personne alors que celle-ci a quitté le labo. Exemple : Charlotte Halpern, qui a quitté le CEVIPOF en 2006, et a rejoint le CEE; elle sort dans l'annexe 4 du CEVIPOF alors qu'elle ne le devrait pas.
