### ISSUE TITLE
Besoin de typer les diplômes

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#224]
A l'heure actuelle, on a un enum pour le type de Distinction qui couvre les distinctions et les diplômes.
On a besoin de tracer certains diplômes tels HDR et doctorat.
Il faudrait donc ajouter un enum pour type les Diplômes uniquement.
Si Type de Distinction = diplôme, double-diplôme ou cotutelle, faire saisir le type de diplôme parmi les enums suivants :
- Doctorat
- HDR
- Master
- Autre
On garde le nom détaillé du diplôme dans l'intitulé.

Du coup, il faudrait aussi modifier l'ordre de saisie des infos dans le formulaire. Il faut commencer par le type de distinction, obligatoire, puis le type de diplôme (obligatoire), puis l'intitulé (facultatif), et la date (facultatif).

**Comment by Yomguithereal** [comment]
Du coup, j'ai mis le type master au diplome précédent dans banner mais est-ce bien le cas @LGAGELIN ?

**Comment by LGAGELIN** [comment]
Dans le fichier d'import des Doctorants, il y a pas mal de diplômes antérieurs différents de Master. 
Donc dans l'idéal, il faudrait typer "Master" tous ceux qui contiennent "Master" (Master, Master 1, Master 2, Master 2 recherche, Master Philo, etc...) et dans "Autre" tous les autres (Licence, Magistère, Ingénieur, Agrégation, Bachelor of Arts, DEA, etc...). La colonne à checker est LIB_DIPL_ADM_L1. On garde le nom complet du diplôme dans People.dstinctions.title (concat de DIPL ADM L1 et DIPL ADM L2)

**Comment by LGAGELIN** [comment]
pas si vite papillon...... il y a aussi des diplômes antérieurs de type Doctorat, qu'il faudrait donc mettre dans "Doctorat". Pour cela, il faudrait checker que LIB_DIPL_L1 contient "Doctorat" ou "PhD" (doctorat d'établissement, doctorat, PhD, doctorat d'état...) et l'envoyer dans "doctorat"

**Comment by LGAGELIN** [comment]
En fait, non, il faut considérer le diplôme antérieur aussi en cas d'HDR. De plus, même quand la ligne concerne un Doctorat, le diplôme antérieur peut également être un Doctorat (doctorat, doctorat d'état, doctorat de 3è cycle). Donc que la ligne concerne un Doctorat ou HDR, il faut inscrire le diplôme antérieur selon les mêmes règles.

**Comment by Yomguithereal** [comment]
Il faut rediscuter les heuristiques à vive voix là parce qu'il y a des cas que tu ne prends pas en compte et qui vont poser problème.

**Comment by Yomguithereal** [comment]
On a discuté.

**Comment by Yomguithereal** [comment]
Veni vidi vici.

**Comment by LGAGELIN** [comment]
On récupère tous les diplômes antérieurs.
