### ISSUE TITLE
Import activités: retirer les dates redondantes dans les affectations de gens & organisations

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#226]
Dans l'import des activités de type Invités, il est inutile d'affecter des dates dans les organisations impliquées (organisation d'accueil et organisation d'origine). En effet, elles sont redondantes avec les dates du séjour indiquées dans le premier bloc et ne sont pas pertinentes sur les organisations.

**Comment by Yomguithereal** [comment]
J'ai changé le nom de l'issue parce qu'il faut répliquer cette logique à toute les activités. Le rationale gardé est le suivant: on indique une date à l'affectation org ou people seulement quand elle est différente de celles renseignées pour l'activité.
