### ISSUE TITLE
Tri par défaut des tableaux : par ordre alphabétique sur la première colonne

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#228]
Les utilisateurs se demandent dans quel ordre les infos apparaissent dans les tableaux. 
Pour les tableaux de personnes, ce qui paraît le plus standard est d'adopter le tri par l'ordre alphabétique sur le nom.

**Comment by paulgirard** [comment]
Peut être peut on trier par défaut sur la première colonne ?
Simple et efficace.
Je demande l'avis de yomgui
