### ISSUE TITLE
Lors de la création d'un objet lié, l'objet n'est pas affiché

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#229]
Lorsqu'on crée un objet Personne ou Organisation depuis une activité ou une personne, rien ne se passe en apparence, la valeur de l'objet créé n'est pas affiché dans le champ d'origine.
Après Save non plus. Il faut rafraichir la page pour voir apparaître le champ rempli.

Pourtant, la donnée est bien créée dans la base.

**Comment by LGAGELIN** [comment]
Problème toujours d'actualité en PPRD. Je rouvre l'issue. Pour reproduire, se connecter en tant que madani.cheurfa (center_admin), créer une organisation de tutelle depuis une organisation.

**Comment by t8g** [comment]
Closed by #291
