### ISSUE TITLE
Style et design des champs multivalués

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#230]
Quand il y a une première valeur dans un champs multivalués, on ne sait pas où cliquer pour ajouter une autre valeur : 
![image](https://cloud.githubusercontent.com/assets/193478/21713981/ff1a6748-d3fc-11e6-9e53-44822bc8b84c.png)

si on trouve, le dropdown n'est pas au bon endroit :
![image](https://cloud.githubusercontent.com/assets/193478/21714001/1e48aa12-d3fd-11e6-8438-553f63b1fbe7.png)

Une fois qu'on a cliqué une fois le label du champs indique la zone où cliquer :
![image](https://cloud.githubusercontent.com/assets/193478/21714016/2ea8194c-d3fd-11e6-842b-594c624b89a0.png)

Tout ça n'est pas bon pour les utilisateurs.

Il faut revoir ce champs.
voir les débuts de propositions décrites à #167 
Problème lié à #82

**Comment by t8g** [comment]
See https://github.com/SciencesPo/isari/commit/aa1148a9dc9014109d854c1092de861f077d51bb
Changement ordre : 

1. input (avec menu tjs en dessous)
2. aide contextuelle
3. les valeurs existantes

Le champ devient plus intuitif : comme les autres champs, on clique sur le label pour éditer.

**Comment by Yomguithereal** [comment]
Ok donc, fonctionnellement le concept marche et on va bien continuer dans ce sens.

Problèmes à régler:

- [ ] : Le label devrait avoir le même comportement qu'avec un input text material classique (se place en haut dès qu'une valeur est settée).
- [ ] : Trouver une autre indication visuelle que l'on peut ajouter une nouvelle valeur (un placeholder générique différent genre "Ajouter une valeur...", mais peut être tricky à implémenter, je ne sais pas.)
- [ ] : Recadrer les icônes liées aux foreign key pour éviter l'overlap avec la valeur.

Bonus:

- [ ] : Il serait cool que la liste de suggestion n'affiche pas des items déjà présents dans la liste (probablement chiant à implémenter donc c'est un bonus que si c'est trivial à faire).

**Comment by t8g** [comment]
Done
