### ISSUE TITLE
Le scroll automatique est aléatoire

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#231]
Depuis le tableau, quand on sélectionne une ligne, le scroll automatique ne fonctionne pas toujours alors que le même navigateur est utilisé (Chrome).

A l'ouverture du tableau, au premier clic sur une ligne, le scroll ne se fait jamais.

Quand on rafraîchit la page, le scroll ne se fait pas

**Comment by t8g** [comment]
Scroll au 1er clic : ok
Scroll sur refresh : en cours

**Comment by t8g** [comment]
Pas sûr qu'il faille fermer cette issue
Le pb sur refresh est tjs là
