### ISSUE TITLE
Besoin de distinguer les noms des onglets ouverts dans le navigateur

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#232]
Lorsque on est dans un tableau, et qu'on a sélectionné une ligne, les objets liés qu'on va ouvrir depuis la fiche s'ouvrent dans des nouveaux onglets. Or ceux-ci sont tous appelés "Isari - Sciences Po". Du coup, l'utilisateur peut se retrouver avec plusieurs onglets sans savoir où il est. Pour pallier à cet inconfort, il serait utile de nommer chacun des onglets avec :
- le prénom Nom de la Personne si on a ouvert une fiche Personne
- le nom de l'Organisation 
- le nom du tableau dans lequel on se trouve : Activités, Personnes, Organisations

**Comment by t8g** [comment]
Done
