### ISSUE TITLE
click en dehors pour sortir de focus

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#234]
Tous les champs n'ont pas encore cette fonctionnalité.

Dans le cas du champs date, c'est implémenté mais dans certains cas comme les dates de rattachement labos 
![image](https://cloud.githubusercontent.com/assets/193478/21714905/b17e899c-d401-11e6-8c9a-728fdce1b830.png)

le click en dehors ne marche pas à moins de suivre cette procédure : 
- clicker dans le champs date
- tester le check en dehors = marche pas
- clicker sur le champs date (partie input et non le dropdown)
- re-tester le check en dehors = marche !

**Comment by t8g** [comment]
Corrigé
