### ISSUE TITLE
Création d'un objet lié multivalué : affichage défecteux

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#236]
Quand on crée un lien dans un champ multivalué, outre le fait que la valeur ne s'affiche pas (cf issue #229  ), les icônes affichés sont décentrés.

![image](https://cloud.githubusercontent.com/assets/22589536/21716354/521ed084-d40a-11e6-8427-977de6615172.png)

**Comment by t8g** [comment]
Corrigé
