### ISSUE TITLE
ajouter le champs nameAcronymeAliases aux recherches de FK d'orga

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#242]
Après l'ajout du champs alias dans les orga voir #223 il faut que la recherche de clef étrangères vers les orga utilise ce champs en plus de name et acronym.

**Comment by Yomguithereal** [comment]
En réalité, la query ES tape sur tous les champs du document par défaut donc nul besoin de se mettre la rate au court-bouillon. Tant que les aliases sont indexés dans ES ça devrait marcher.

**Comment by LGAGELIN** [comment]
ça marche pas très bien. On dirait que si il y a un "Acronyme" et un champ "Autres noms" renseignés, la recherche via FK ne tient pas compte de l'acronyme. Exemple sur la PPRD, sur une fiche People dans le bloc Activités Personnelles, chercher l'organisation "ENS Paris" (acronyme) = > elle n'est pas remontée 
mais si on cherche Ulm (autres noms) =>  Ecole normale supérieure est bien remontée

**Comment by Yomguithereal** [comment]
Ca en tient compte mais la recherche a d'autre problèmes qui empêchent l'acronyme de remonter. Je laisse fermer et je passe le problème sur la search ES.
