### ISSUE TITLE
Trois petit bugs de style

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#246]
Problème de taille des icônes : 
![image](https://cloud.githubusercontent.com/assets/193478/21806806/c116b3e2-d73b-11e6-94ec-0040c71c0b61.png)

Il reste du violet :
![image](https://cloud.githubusercontent.com/assets/193478/21806820/d5977d24-d73b-11e6-8f01-1736d43c02b8.png)

![image](https://cloud.githubusercontent.com/assets/193478/21936601/0f0395ca-d9b2-11e6-8e35-e2d42cf416ff.png)

**Comment by t8g** [comment]
La taille des icônes : fait.
Par contre je ne vois que 2 bugs dans la description et non pas 3.

**Comment by t8g** [comment]
Couleur sur pagination : fait.
Je ne ferme pas tant que je ne sais pas quel est le 3eme bug.
