### ISSUE TITLE
Import des contrats : tenir compte d'un séparateur pour importer des valeurs multiples de grants.organization

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#254]
Dans le fichier Contrats, on a une colonne grants.organization qui contient la majeure partie du temps une seule valeur, mais parfois plusieurs, mais celles-ci n'étaient pas normées. Parfois le séparateur est "-", parfois ",".
Du coup, ces valeurs multiples ont été importées dans un seule organisation.
Les voici :
Labex, CNAF, DGCS, France Stratégie, Fondation des Apprentis d'Ateuil, Assemblée Nationale
Ministère de la justice, Agence Nationale De La Recherche
Open Society Institute - Soros Foundation
Mission Droit et Justice, Ministère de la Justice
Institut National De La Recherche Agronomique - DIM ASTREA
Centre National De La Recherche Scientifique, Pôle emploi

Action corrective : le fichier contrats a été mis à jour, les valeurs multiples sont séparées par ";".
Il faut maintenant en tenir compte dans le code d'import :)

**Comment by Yomguithereal** [comment]
Quid de cette valeur là du tableau:

```
CAPES/COFECUB
```

Et de celle-ci:

```
SNC, POLE EMPLOI
```

**Comment by Yomguithereal** [comment]
De plus, je remarque que le schéma considère actuellement qu'un grant n'a qu'une organisation liée. Donc, faut-il revoir le schéma (cc @paulgirard)?

**Comment by LGAGELIN** [comment]
CAPES/COFECUB : une seule valeur, laisser comme ça

SNC, POLE EMPLOI : 2 valeurs, à séparer par un ";" dans le fichier source. Sorry pour cet oubli

Du coup, oui en effet, le schéma devrait être modifié, à vérifier avec Paul.

**Comment by paulgirard** [comment]
La logique voudrait de laisser le schéma tel quel puisque les infos de grant comme les montants sont d'après moi toujours liés à une seul orga.
On peut cependant créer plusieurs objet grant avec une orga mais c'est lourd.. 

La plupart des cas à orga multiples sont très peu détaillées dans les données.
Il n'y a qu'une dizaine de cas.

Il faut commencer par vérifier les cas et se demander si ce ne sont pas plus des partanaires que des multiples financeurs.
A vérifier avec Sophie j'imagine.

**Comment by LGAGELIN** [comment]
Je viens de parler à Sophie, qui a confirmé les modifications suivantes :
- Open Society Institute - Soros Foundation => c'est la même orga, à modifier en : **Open Society Institute (Soros Foundation)**
- Mission Droit et Justice, Ministère de la Justice=> idem, même orga : **Mission Droit et Justice (Ministère de la Justice)**

Pour les autres, elle va vérifier avec les labos concernés au cas par cas.

**Comment by Yomguithereal** [comment]
On a besoin d'une décision ici.

**Comment by LGAGELIN** [comment]
A ce stade on ne modifie pas le schéma. On en avait parlé avec Sophie, elle attend une réponse des centres, mais je dirai qu'à ce stade, on ne touche à rien. Les orgas avec les noms à rallonge contenant des ";" seront modifiées manuellement.
