### ISSUE TITLE
Avec des droits de consultation uniquement, chevauchement des infos affichées dans Diplômes et Distinctions

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#262]
Connecté en tant que membre de labo sur la fiche d'une autre Personne, l'organisation et le Pays du Diplôme/Distinction ne sont pas correctement affichés.
Exemple connecté en tant que Laurent Bonnefoy, ouvrir la fiche d'Emilie PROUST.

![image](https://cloud.githubusercontent.com/assets/22589536/22016649/556c3678-dca7-11e6-9822-5272a4fa027e.png)

**Comment by LGAGELIN** [comment]
Toujours d'actualité

**Comment by LGAGELIN** [comment]
Impec

**Comment by t8g** [comment]
Corrigé
