### ISSUE TITLE
Modification d'informations, la sauvegarde par ctrl S ne s'effectue pas si on ne sort pas du champ

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#263]
Dans une fiche People, quand on saisit un nom de naissance, un téléphone, un numéro de bureau, ,..... la sauvegarde ne se fait pas via ctrl s si on ne sort pas de la zone du bloc du champ modifié. En revanche, si on clique sur Sauvegarder, cela fonctionne.

Exemple : si on modifie le nom de naissance, il faut cliquer ailleurs, par exemple sur le bloc coordonnées, puis sur ctrl s poru que la sauvegarde soit effectuée.
SI on reste dans le champ Nom de naissance et qu'on tape ctrl s, il ne se passe rien.

A relier au #258 ?

**Comment by paulgirard** [comment]
le CRTL+S pourrait blur le champs.
Et hop réglé

**Comment by t8g** [comment]
Corrigé

**Comment by Yomguithereal** [comment]
Pas de race condition à la sauvegarde? Le blur est bien pris en compte avant que le formulaire ne tente de sauver?
