### ISSUE TITLE
Habiller le modal de warning dans les cas d'effacement d'un sous-objet

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#265]
Le modal  de suppression d'un sous-objet (#144)fonctionne bien. il n'y a plus qu'à l'habiller  ;)
Il faudrait également enlever la boîte bleue qui entoure l'icône "Trash" dans el cas où on a annulé la suppression.

![image](https://cloud.githubusercontent.com/assets/22589536/22022331/cd8454e6-dcc1-11e6-8c75-34a34945d42c.png)

![image](https://cloud.githubusercontent.com/assets/22589536/22058948/24f2321c-dd6b-11e6-886e-808d96eade32.png)

**Comment by adriencossonscpo** [comment]
Est-ce mieux comme cela ? (Je me suis occupé de la boîte bleue entourant l'îcone "Trash")

![confirmsupress](https://cloud.githubusercontent.com/assets/22099759/22368517/2c29efa2-e487-11e6-8bdc-78cb6b41b82c.png)

**Comment by paulgirard** [comment]
ajouter un indicateur de focus sur le ok ou annuler
