### ISSUE TITLE
fusionner les éléments contiguës de même nature dans les séries temporelles en fin d'import ?

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#269]
Exemple à l'école de droit : 
![image](https://cloud.githubusercontent.com/assets/193478/22067055/e9207a62-dd8f-11e6-8864-4a7cf79ae9e0.png)

Voir ce bout de code qui règle le problème pour les grades extrait du SIRH : 
https://github.com/SciencesPo/isari/blob/dev/scripts/import/files/people.js#L200

**Comment by Yomguithereal** [comment]
Lié à #268.
