### ISSUE TITLE
largeur à 100% pour les blocs multiples

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#270]
On ne souhaites pas mettre des blocs multipls en colonne avec d'autres à côté.
Du coup ce serait plus élégant que ces blocs multiples prennent toute la largeur du formulaire quelque soit leur composition interne.

Voici un exemple de deux blocs avec des largeurs différentes que l'on aimerait unifier avec une largeur max pour tous les blocs.

![image](https://cloud.githubusercontent.com/assets/193478/22067842/34751c0e-dd93-11e6-866b-61f25e52f46b.png)

**Comment by t8g** [comment]
Je pense que c'est corrigé
