### ISSUE TITLE
Save error lors de la sauvegarde d'enums nested

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#274]
Lors de l'ajout d'une Personne impliquée sur une Activity, la sauvegarde fonctionne; mais si on ajoute ensuite le rôle de la personne, on obtient un Save Error.
Cela ne se produit pas si on sauvegarde directement le lien vers la personne en même temps que son rôle.

Reproduit également lors d l'ajout d'un Statut et grade sur une Personne. Ajouter lle Statut, sauvegarder OK, puis ajouter le Grade => Save Error.
Même chose si on ajoute les 2 en même temps la sauvegarde se fait bien.

**Comment by t8g** [comment]
Non reproduit sur l'activité.

1. édition d'une activité
2. ajout d'une personne impliquée (sans rôle)
3. sauvegarde - OK
4. ajout d'un rôle
5. sauvegarde - OK

**Comment by Yomguithereal** [comment]
Version de Mongoose?

**Comment by LGAGELIN** [comment]
Je n'ai plus cette erreur avec ce scénario. En revanche, il y en a d'autres

**Comment by t8g** [comment]
Je ferme donc en faveur de #287
