### ISSUE TITLE
Revoir les méthodes de recherche des personnes ou orga depuis les fiches People et Activités

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#281]
Recherche des organisations depuis une fiche People ou Activité ne donne pas satisfaction. Idem pour la recherche de Personne.

Si on saisit le nom exact de l'entité recherchée, le système propose toujours une liste au lieu de la limiter à une seul entrée.

**Comment by paulgirard** [comment]
Nécessaire de régler ce problème pour #157
