### ISSUE TITLE
Check Import ORCID & Scopus ID

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#285]
Exemple : Ni l'ORCID ni le scopus ID de Carlo Barone n'apparaît dans aucune de ces fiches Carlos Barone / Carlo Barone

**Comment by Yomguithereal** [comment]
Dommage.

**Comment by Yomguithereal** [comment]
Probablement parce que je n'arrive pas à le récupérer dans le ldap alors que j'ai besoin du ldap uid pour pouvoir le matcher dans le fichier des ids.

**Comment by LGAGELIN** [comment]
Toujours pas d'ID ORCID ni Scopus ID pour Carlo Barone . Pourtant, on n'a bien qu'une seule fiche People pour lui suite au clustering.

**Comment by Yomguithereal** [comment]
J'en ai bien un dans mes données import. Probablement fixé mais pas sur pprd. Par contre j'ai toujours une liste de gens non matchés dans ORCID. Je te l'envoie par mail.
