### ISSUE TITLE
Erreur à la sauvegarde lors de l'ajout d'un Diplôme ou Distinction 

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#286]
Sur une fiche People, ajouter un Type de Distinction, sauver =>Save error
Cela se produit systématiquement, même en changeant de scénario : ajouter le Type de Distinction, le type de diplôme, et saisir l'intitulé => Save error

**Comment by LGAGELIN** [comment]
A priori si on sort du champ, on n'a pas le problème. Du coup à checker, mais ça devrait être corrigé via le #263

**Comment by t8g** [comment]
À priori ça semble bon.

**Comment by LGAGELIN** [comment]
On n'a plus de Save Error, en revanche, si on vide les champs Type de distinction et Type de diplôme, après la sauvegarde, et rafraîchissement, ils sont toujours remplis.

**Comment by LGAGELIN** [comment]
Devrait être fixé avec le #287 . A tester

**Comment by LGAGELIN** [comment]
ça marche nickel :+1:
