### ISSUE TITLE
La sauvegarde ne se fait pas quand on vide un champ

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#287]
Sur une Activity, Ajouter un lien sur une Personne, avec un rôle. Sauvegarder.

Puis vider le rôle => la sauvegarde ne s'effectue pas.

**Comment by t8g** [comment]
Il me semble que c'est corrigé.
Peux-tu vérifier ?

**Comment by LGAGELIN** [comment]
ça marche mieux, en revanche, si on vide le champ Rôle, la modification n'est pas enregistrée

**Comment by Yomguithereal** [comment]
C'est fixé

**Comment by LGAGELIN** [comment]
ça marche nickel :+1:
