### ISSUE TITLE
Indication de champ obligatoire disparaît

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#288]
Sur une Activity, ajouter un financement, le champ montant est bien indiqué comme obligatoire. Sauvegarder, puis éditer le montant, vider le champ, il n'apparaît plus comme obligatoire. Du coup on a une erreur à la sauvegarde, mais on ne sait pas pourquoi.

On a aussi le problème sur les champs Enums. Exemple avec le Statut dans People, obligatoire quand on ajoute un Statut et Grade. Puis quand on a sauvegardé, et qu'on vide le champ Statut, il n'est plus indiqué comme obligatoire.
![image](https://cloud.githubusercontent.com/assets/22589536/22286987/65395d38-e2f1-11e6-967a-d505d965461f.png)

**Comment by t8g** [comment]
Fait pour input type number

**Comment by LGAGELIN** [comment]
Je confirme c'est OK pour le montant des financements.
