### ISSUE TITLE
première version de editlogs

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#3]

**Comment by naholyr** [comment]
Version rudimentaire mise en place, la principale difficulté étant de lier la session utilisateur, du coup c'est fait "à la main" avant d'appeler une méthode du modèle :

```js
doc._elWho = "Identifiant de l'utilisateur connecté"
doc.save() // Ajoutera une entrée dans "editlogs"
```

Quand `_elWho` n'est pas défini on a un gros pavé jaune de warning dans la console, avec une stack qui devrait théoriquement aider à détecter ces mauvaises utilisations et les corriger.

Les schéma de `editlogs` se trouve ici : https://github.com/SciencesPo/isari/blob/dev/server/lib/edit-logs.js#L7-L29

**Comment by paulgirard** [comment]
Ok j'ai renommé en première version et je clos. J'ai ajouté une autre carte pour la suite.
