### ISSUE TITLE
Faire le tour des TODO du code d'import

### ISSUE THREAD

**Issue by Yomguithereal** [SciencesPo/isari#302]

**Comment by Yomguithereal** [comment]
Il reste:

1. La question des organisation fantômes.
2. La question du merge des périodes overlap.

**Comment by Yomguithereal** [comment]
@LGAGELIN quid des orga fantômes? On les garde pour invités? Il faut en faire pour sejours?

**Comment by LGAGELIN** [comment]
Pour les séjours c'est sûr que non. Pour les invités, j'ai besoin de voir ce que donne les orgas fantômes sur la PPRD mais pour l'instant je n'y accède pas.

**Comment by LGAGELIN** [comment]
Je viens de voir ce que donnent les organisations fantômes sur les Invités. Le mieux serait de les virer dans l'import. Pas d'organisation d'origine dans le fichier Invités = on ne crée pas d'organisation.

**Comment by LGAGELIN** [comment]
Ok vu en PPRD
