### ISSUE TITLE
Sauvegarde états applicatifs choix colonnes + ouverture bloc layout

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#305]
Stocker dans le local storage :
- [x] Choix des colonnes
- [x] État ouverts des blocs de layout 
- [ ] état du filtrage (dates, filtres...)

Recharger l'etat à la réinitialisation de l'interface.

L'idée est que ces deux choix forment un usage particulier. Il faudrait que cet usage survive au rechargement de la page voire déconnexion.

**Comment by LGAGELIN** [comment]
Je le mets en Indispensable, car c'est assez pénible de perdre les colonnes du tableau poru l'utilisateur (vu avec la DS)

**Comment by t8g** [comment]
Attention avec la date du jour

**Comment by t8g** [comment]
- [x] Choix des colonnes
- [ ] État ouverts des blocs de layout 
- [ ] état du filtrage (dates, filtres...)

**Comment by LGAGELIN** [comment]
Pouvez-vous indiquer comment cela fonctionne ? La mémorisation des informations est liée au navigateur, pas au compte user?
En gros si je me connecte sur le poste de quelqu'un de la DS, je vais voir les colonnes état des blocs, et filtres de l'utilisateur de la DS, pas les miennes ?

**Comment by paulgirard** [comment]
oui c'est bien ça.
état enregistré par navigateur et non par session utilisateur.

**Comment by LGAGELIN** [comment]
Est-ce que ce serait faisable facilement de garder aussi le nombre d'objets ramenés dans le tableau ?
