### ISSUE TITLE
Une fois que la Personne est créée, la popup reste persistente sur l'onglet d'origine

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#309]
Créer un personne, cliquer sur continuer => on ouvre bien la nouvelle fiche sur un autre onglet. 
Cliquer sur l'onglet d'origine, la popup est toujours présente. Cela surprend un peu. et le résultat de recherche de la popup est faux du coup

**Comment by LGAGELIN** [comment]
#315

**Comment by t8g** [comment]
Done
