### ISSUE TITLE
bug in format model-utils.js

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#31]
GET /people/58122907ce7b16389db7008f 500 31.496 ms - 1494
GET /layouts/people 304 29.899 ms - -
TypeError: Cannot read property '0' of null
    at Object.keys.forEach.f (/home/pgi/dev/isari/server/lib/model-utils.js:145:40)

On n'a regardé et à priori la récursion ne s'arrête pas à temps à cause du test ligne 123 : 
```js
if (!isObject(object)) {
```

les champs qui contiennent des ref ressemble à des string d'id mongo.
Mais en fait ce ne sont pas des strings mais des OjectId mongoose.
Ces objets ont un paramètre id qui est un buffer !

du coup ça crash.
et du coup si on essaie de gérer ce cas dans le dit-test ça cascade à d'autres bugs... 

On laisse @naholyr regarder ça avec son cerveau entrainé

**Comment by naholyr** [comment]
Le commit fixe bien le problème a priori, pour détailler le fonctionnement, selon le niveau rencontré on peut avoir les cas suivants :

* Un objet instance de modèle (objet racine ou ref peuplée) → on formate avec le schéma correspondant au modèle, on garde l'id dans le résultat
* Un objet (sous-document) qui n'est pas une instance de modèle → on formate avec le schéma du champ correspondant (on parcourt le schéma en parallèle de l'objet), on ne garde pas l'id dans le résultat s'il y en avait un
* Un tableau → on formate chaque élément avec le schéma correspondant (normalement le schéma est alors aussi un tableau d'un élément qui est le schéma à suivre)
* Une valeur scalaire → inchangé

Le bug venait du fait que lors du parcours parallèle objet/schéma, parfois le schéma n'existe pas. Le fix a l'air de fonctionner néanmoins ça peut être le symptôme d'un objet invalide. Par exemple people.firstname → schema.firstname n'existe pas, est-ce qu'on ignore lors du formatage ou est-ce qu'on lève une erreur ?
En l'état actuel le formatage est donc permissif, les champs sans schéma sont laissés tel quel, je pense que ça peut être acceptable dans le sens où normalement à ce stade du cycle de vie de l'appli on ne devrait pas avoir de données aberrantes. Et c'est de la lecture, on n'a pas envie d'être embêté par des messages d'erreur, on veut la data même si elle n'est pas complète.

**Comment by paulgirard** [comment]
Oui il faut rester permissif en lecture voir en écriture pour ce qui est des champs non connus.
On verar ce point bien plus tard quand on envisagera des évolutions de schéma.
