### ISSUE TITLE
Une fois créée, une nouvelle Organisation/Personnes/Activité n'est pas trouvée par la recherche dans le tableau

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#310]
Il faut rafraîchir la page des Organisations sans quoi la nouvelle organisation créée n'est pas trouvée.

**Comment by paulgirard** [comment]
Le problème est vrai aussi si on modifie un champs visible dans le tableau dans une fiche.
Si on veut maitnenir le tableau à jour il faudrait le recharger à chaque modifications (voir même à chaque modif de n'importe quel user). Donc c'est soit très lourd soit carrément pas possible.

Donc disons que le tableau est un état figé.
Ajoutons un bouton pour rafraichir l'état.
L'utilisateur peut rafraichir si il le souhaite ou pas.
Je clos voir #336
