### ISSUE TITLE
Bloquer l'export HCERES pour Sciences Po ou habiller le message d'erreur

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#311]
A l'heure actuelle, si on demande l'export HCERES pour Sciences Po, on obtient une erreur, ce qui est "normal", il faudrait soit bloquer l'export si on est sur Sciences Po (masquer le bouton), soit habiller l'erreur.

![image](https://cloud.githubusercontent.com/assets/22589536/22552734/720443a6-e95a-11e6-9a24-6d34d868c9c3.png)

**Comment by Yomguithereal** [comment]
J'ai caché le bouton quand on est sur Sciences Po c'est bon.
