### ISSUE TITLE
Voir pourquoi Carlo Barone n'a pas d'identifiant annuaire LDAP sur la PPRD

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#314]

**Comment by LGAGELIN** [comment]
Mais c'est correct en PROD, on a tout.

**Comment by Yomguithereal** [comment]
Je pense que ça dépend du LDAP interrogé. En pprd le ldap n'est pas le même et n'as peut-être pas Carlo Barone.
