### ISSUE TITLE
Suppression d'une Personne/Activité/Organisation : pas de rafraichissement

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#315]
Le système demande la confirmation de la suppression, mais ne rafraîchit pas la page. Résultat on reste sur la fiche alors que celle-ci a été supprimée. C'est un peu déroutant.

Dans l'idéal, il faudrait revenir au tableau correspondant au type de fiches créées.

**Comment by paulgirard** [comment]
cas présent uniquement quand on supprime une fiche ouverte dans un onglet cad quand on regarde son profil ou quand on vient de créer la fiche.
autant dire que ce n'est pas courant.

On peut dans ces cas tenter de rediriger vers le tableau correspondant.

**Comment by t8g** [comment]
Done
