### ISSUE TITLE
Réduire la taille de la police des 2 filtres de Dates

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#317]
Le requêteur de dates est bien, on cherche juste à harmoniser son aspect avec les colonnes du tableau. 
Utiliser la même police et la même taille de police.

![image](https://cloud.githubusercontent.com/assets/22589536/22591273/f8c54570-ea13-11e6-9554-9bce846a69c7.png)

**Comment by t8g** [comment]
Done
