### ISSUE TITLE
Avec le rôle Direction Générale, on arrive à ajouter des fiches

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#318]
Avec le rôle Direction Générale, les boutons Ajouter Personnes/Orga/Activités sont visibles, et on peut sauver les nouvelles fiches sans problème.

Dans l'idéal, ils ne devraient pas voir ces boutons ou ils devraient être inopérants.

mettre la restriction côté front et côté serveur.

**Comment by paulgirard** [comment]
C'est le rôle qui est utilisé pour mettre les formulaires en lecture seule

**Comment by t8g** [comment]
Si central === 'reader' Alors bouton "créer" non affiché.
