### ISSUE TITLE
Impossible de modifier la fiche de Charline Avenel

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#319]
Sur la PROD et sur la PPRD, il y a un problème à la sauvegarde des modifications de la fiche Charline Avenel. On a un Save error systématique.

Sur la PROD, on a supprimé la fiche et on l'a recréée car on n'arrivait pas à faire les modifications (on voulait supprimer son academic membership à la DS).

Sur la PPRD, on n'y a pas touché.

**Comment by paulgirard** [comment]
mystère résolu. C'est le même cas que #348
