### ISSUE TITLE
enlever les listes vides des retours d'API (généré côté mongoose ?)

### ISSUE THREAD

**Issue by naholyr** [SciencesPo/isari#32]

**Comment by naholyr** [comment]
* Quand on a un objet dont le schéma comporte `champ: […]` (champ multiple), alors Mongoose affecte un tableau vide par défaut
* Ça ne se produit qu'au moment de la lecture

```js
o.champMultiple = undefined
o.save()
// Dans mongo: champMultiple est bien undefined
Model.findById(o.id) // champMultiple = [], grmbl
```

Il faut donc :

* trouver un moyen de *savoir* si le champ est effectivement `[]` ou s'il était `undefined`
* rétablir la bonne valeur, au moins au moment de la sortie pour l'API

**Comment by naholyr** [comment]
A priori il n'existe aucun moyen de savoir si le champ était déjà `[]` à l'origine, ou simplement non défini. 

Après réflexion, il vaut peut-être mieux les laisser :

* Avantages :
  * Le front a toujours un tableau, on peut compter dessus pas besoin de `if`
  * On évite des modifications d'objets
  * On sera destructifs dans tous les cas : si on a souhaité affecter `champMultiple = []` explicitement, on n'a pas le moyen de le savoir et il sera remis à `undefined`
* Inconvénients :
  * Plus de data retournée par l'API
  * Des tableaux vides sans sens dans mongo à chaque *resave*

Ping @paulgirard pour quoi qu'on fait

**Comment by paulgirard** [comment]
Ok on garde comme c'est
