### ISSUE TITLE
Ajouter une colonne Pays du dernier diplôme dans le Tableau des Personnes

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#322]
Besoin de la DS, vu avec Sophie et Bénédicte. Il s'agit d'une info suivie à la DS dans le cadre du contrat quinquennal avec le MESR. Sans cette info, la DS serait obligée de continuer à utiliser les fichiers DS academic....

**Comment by paulgirard** [comment]
On envisage de créer un export spécifique "facultépermanente" qui regroupe plein de colonnes utiles et spécifiques pour la DS.
On attend le récolte de besoin de Sophie et on planifie cet export.
