### ISSUE TITLE
Rattachement labo non à jour quand on requête sur les Dates

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#325]
Exemple : Adam SCHAAL est affilié au CDSP de 2010 à 2013.

Si on requête sur Date de fin seulement = 2011, il est bien dans les Membres, mais on perd l'info du rattachement au CDSP dans le tableau. Pourquoi ? On devrait considérer qu'il est toujours au CDSP.
![image](https://cloud.githubusercontent.com/assets/22589536/22734147/003b8bb8-edf5-11e6-8c5b-a98119336868.png)

**Comment by paulgirard** [comment]
c'est le même problème que #320 
Corriger l'un corrigera l'autre si tout va bien

**Comment by LGAGELIN** [comment]
ça semble OK
