### ISSUE TITLE
Permettre le suivi des départs de la communauté scientifique

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#326]
La DS a besoin de suivre les départs de la communauté scientifique. Il faut voir avec Sophie ce qui est le plus pertinent : ajouter 2 colonnes dans le tableau des Personnes, Date du dernier départ,  motif de départ, ou faire un export spécifique qui réponde au besoin d'indicateurs.

**Comment by paulgirard** [comment]
on ajoute une colonne facultyMonitoring #332 et un export spécifique voir #322 
Je clos celle là
