### ISSUE TITLE
Bug filtrage dates et activités de sciences po

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#327]
Sur Sciences Po, Séjours à l'étranger, Date début = 18 sept 2014

en fait ça ne marche pas sur Sciences Po,  le système ne renvoie rien. Ceci va être embêtant pour la DS, par exemple sur les projets de recherche. 

![image](https://cloud.githubusercontent.com/assets/22589536/22589503/e825b406-ea0a-11e6-81cf-71c75017e6b0.png)

**Comment by LGAGELIN** [comment]
ça semble OK
