### ISSUE TITLE
sélecteur de dates Bug

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#328]
Dans le sélecteur de date on commence avec ce choix de dates :

![image](https://cloud.githubusercontent.com/assets/193478/22885111/3cbf55b8-f1f8-11e6-853a-c73a9ad293a2.png)

Si on veut une année plus récente on clique sur la flèche de déplacement vers la gauche.
La dernière année disponible sur cette page de gauche est 2009 et non 2011.
Il manque 2010 et 2011. Elles réapparaissent si on se déplace d'une page vers le droite...

**Comment by t8g** [comment]
done
