### ISSUE TITLE
réflexion sur l'editlogs Quoi stocker et comment ?

### ISSUE THREAD

**Issue by naholyr** [SciencesPo/isari#33]
Rappel, une entrée dans la collection `EditLogs` a les propriétés suivantes :
- `model` : nom du modèle concerné, donc `People`, `Organization` ou `Activity`
- `date` : date de l'édition
- `action` : l'édition effectuée, `create`, `update` ou `delete`
- `who` : l'auteur de l'édition, pris depuis le champ `latestChangeBy` de l'objet concerné
- `data` : les données concernées, objet de cette issue
### Création
- Actuel : tout l'objet
- Devrait être : tout l'objet ?
### Mise à jour
- Actuel : tout l'objet
- Devrait être : seulement les champs modifiés ?
### Suppression
- Actuel : tout l'objet
- Devrait être : seulement l'ID ?
## Scénarios d'utilisation d'edit-logs
- Consultation de la dernière édition d'un objet :
  - On a plutôt envie de ne voir que les modifications ou au moins d'y avoir un accès rapide
- Reconstruire un objet supprimé :
  - Si on ne stocke que les modifications, on devra rejouer tous les _update_s depuis sa création
- Autre scénario ?

**Comment by paulgirard** [comment]
Il faut remplacer data par un champs diff.
Ce champs doit comporter la liste des modifications unitaires par champs.

Les deux usages principaux sont : 
- permettre de retrouver la liste des modificatiosn qui ont impactés une liste de champs du schéma (taggué comme condifential)
- lister l'historique d'un objet dans le formulaire

**Comment by Yomguithereal** [comment]
j'ai commité un alignement sur la branche `edit-log`.

**Comment by Yomguithereal** [comment]
Reste à résoudre #22.
