### ISSUE TITLE
accent et filtrage tableau 

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#331]
Dans le filtrage du tableau, les accents sont pris en compte.

On aimerait que les voyelles non-accentuées dans le champs de filtrage renvoient les valeurs avec accents.

Même problème avec la recherche sur elasticsearch (création de personne, création de lien...)

**Comment by paulgirard** [comment]
un filtre sur jeremy doit renvoyer jérémy
un filtre sur jérémy doit renvoyer jeremy

**Comment by Yomguithereal** [comment]
`_.deburr` est ton ami.

**Comment by t8g** [comment]
Oh merci. J'avais pas vu ton message j'ai ajouté un truc dans utils
Je vire pour deburr

**Comment by t8g** [comment]
Et hop avec deburr ;) Merci @Yomguithereal

**Comment by t8g** [comment]
Fait aussi sur les query de ES
