### ISSUE TITLE
ajouter une colonne facultyMonitoring

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#332]
Cette colonne contient : 
facultyMonitoringType date séparé par virgule

Seulement ceux qui matchent la période de temps.

**Comment by LGAGELIN** [comment]
Non disponible en PPRD, c'est embêtant pour tester avec les différents rôles.

**Comment by LGAGELIN** [comment]
Je croyais que la fonctionnalité n'était pas dispo en PPRD car j'étais connectée en tant que simple Membre. et ne voyais pas cette colonne. Du coup je confirme que ça fonctionne bien en fonction des rôles, on peut voir ou pas cette colonne apparaître.
