### ISSUE TITLE
régression select foreign key

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#339]
pour reproduire : 
- dans le champs nationalité
- tapper françai
- l'enum réordonne correctement
- si on clique sur française en faut de la liste : tout en ok 
- si on tape entrée deux problèmes 

- [x] c'est l'ancienne valeur en haut de liste "andoranne" qui est sélectionnée
- [ ] le save est triggered

**Comment by t8g** [comment]
save triggered on enter : see #341
