### ISSUE TITLE
gestion des droits dans l'API

### ISSUE THREAD

**Issue by naholyr** [SciencesPo/isari#34]
Voir la doc [specs/docs/role_access.md](https://github.com/SciencesPo/isari/blob/master/specs/docs/role_access.md)
Attention dette issue est plus à jour que la doc.

J'avais tenté de décrire les rôle et accès dans ce fichier [specs/role_access.json](https://github.com/SciencesPo/isari/blob/master/specs/role_access.json). Je propose d'abandonner l'idée d'avoir une conf de ce type... Écrivons les règles directement dans le code. A moins qu'un tel fichier puisse aider ? 

Logique :
- [x] Qu'est-ce qui définit la permission d'un utilisateur sur un objet ?
  - [x] aucun utilisateur ne peut se connecter si il n'a pas une fiche
  - [x] le champs isariAuthorizedCenters définit le rôle de l'utilisateur *→ cf. `req.userRoles`*
  - [x] Attention pas de filtrage par rôle dans l'autocomplete
- [x] Définition périmètre d'un centre
  - [x] les objets people sont dans le périmètre d'un centre si cette orga est dans academicMemberships
  - [x] les objets people qui n'ont pas de academicMemberships en cours avec une liste d'orga de SciencesPo (cad qui ont u flag à la con dans le schém tbd) sont partagés en écriture par tout le monde.   
  - [x] les objets activity sont dans le périmètre d'un centre si cette orga est dans organisations
  - [x] les orga sont accessibles à tout le monde
- [x] Isolation People : 
  - [x] un people est bloqué en écriture aux autres usagers
  - [x] un people est inscriptible aux admins et au user lié
- [x] Qu'est-ce qui définit la permission d'un utilisateur sur un champ ?
  - [x] seule exception les champs "accessType": "confidential" (voir la doc)
  - [x] ce pourrait être util d'ajouter une option "accessType":"protected" qui réserverait l'écriture de certain champs aux admins; (non présent à ce jour dans le schéma mais ce ne serait pas idiot de l'utiliser sur les identifiants par exemple).

Côté API :
- [x] Objet inaccessible → 403
- [x] Objet en lecture seule → `opts.editable = false`
- [x] Objet en lecture/écriture → `opts.editable = true`
- [x] Champ inaccessible → non présent dans le JSON renvoyé par l'API

- [x] Champ en lecture seule → ???
- [x] Champ en lecture/écriture → ???
=> A ce jour on n'a pas le cas mais ce serait bien de le prévoir (voir ci-dessus l'idée d'une option "accessType":"protected"

**Comment by paulgirard** [comment]
Attention pas de filtrage par rôle dans l'autocomplete

**Comment by naholyr** [comment]
Note : rendre la gestion des droits désactivables (comme auth ldap)

**Comment by paulgirard** [comment]
J'ai créé un champs booléen dans orga pour préciser les orga internes. Ce sera util pour cette partie : 
" les objets people qui n'ont pas de academicMemberships en cours avec une liste d'orga de SciencesPo (cad qui ont u flag à la con dans le schém tbd) sont partagés en écriture par tout le monde."

ce commit implique cette issue #81

**Comment by naholyr** [comment]
Notion de rôle "global" (central) : si *un* des `isariAuthorizedCenters.isariRole` vaut `central_admin` ou `central_reader`, c'est un utilisateur dit "central". Impact : un lien dans sa home pour accéder au mode "non scopé" des people/activities.

**Comment by naholyr** [comment]
Permissions sur un people : chaque entrée de `academicMemberships` dont `endDate` < maintenant et `organization.isariMonitored` est vrai indique que la personne "appartient" à cette organisation et ne peut être modifiée que par les admins de cette organisation et elle-même.

**Comment by paulgirard** [comment]
Je note les deux derniers points qui posent problème à notre connaissance: 
- comment accéder aux people domaine public genre juste après l'avoir créé ?
- faut il vraiment empêcher de voir les FK protégé ? et si oui comment ? 

On va réfléchir à ça.

**Comment by paulgirard** [comment]
Je déclare clos.
Je passe ce qui doit bouger dans le milestone debug.
