### ISSUE TITLE
deux petite modifs dans schéma et enums

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#340]
- [x] le champ "département d'enseignement" apparait comme "obligatoire" : je ne pense pas que ce soit nécessaire, est-ce qu'il serait possible d'enlever la mention obligatoire ?
- [x] dans le bloc "financement" des activités, l'enum du champ "statut" est restée en anglais. Est-ce qu'il serait possible de traduire les labels ? Voilà ce que je propose : submitted > soumis, accepted > accepté, ongoing > en cours, rejected > non retenu

**Comment by LGAGELIN** [comment]
OK  corrections vues en PPRD
