### ISSUE TITLE
impossible de sauvergarder les modifications sur une fiche personne

### ISSUE THREAD

**Issue by sophiejacquot** [SciencesPo/isari#348]
Fiche de Bénédicte HERAUD, OSC. Elle est partie de Sciences Po en 2016.
Lorsque que l'on indique 2016 comme date de sortie dans les blocs "centre de recherche" + "statut" + "parcours" (dans un seul des blocs ou dans les 3 à la fois) -> save error

**Comment by paulgirard** [comment]
C'est lié à un problème généré à l'import.
Cette personne à une date de naissance mais avec une valeur "null".
elle devrait pas avoir de date de naissance du tout. 
Du coup ça ne passe pas la validation du formulaire (alors que ça a passé celle de l'import..)

Deux solutions : 

- à très court terme il suffit de mettre une date de naissance puis de la supprimer pour contourner le problème
- à moyen terme il faut qu'on supprime tous les champs null de la base en prod. Pour cela il faut faire un script et l'appliquer sur la prod.

Je vois avec Jérémy quand on peut faire ça.

**Comment by paulgirard** [comment]
il n'y a que 11 cas.
A résoudre à la main donc.

**Comment by paulgirard** [comment]
fait par Sophie en prod
