### ISSUE TITLE
téléchargement des informations affichées dans le tableau

### ISSUE THREAD

**Issue by sophiejacquot** [SciencesPo/isari#350]
Je cherche à obtenir la liste des projets de recherche qui ont débutés en 2016.
Afin d'obtenir cette information : sélection des projets de recherche, puis filtre "2016" dans le tableau, colonne "date de début" (cf capture d'écran).
 = problème : l'action "télécharger" dans cette configuration donne un fichier qui comprend l'ensemble des projets de recherche et non pas seulement ceux qui sont affichés dans le tableau (cf fichier excel téléchargé en PJ).

[capture.pdf](https://github.com/SciencesPo/isari/files/783500/capture.pdf)
[activities-2.xlsx](https://github.com/SciencesPo/isari/files/783502/activities-2.xlsx)

**Comment by paulgirard** [comment]
cela n'arrive que qu'un paramètre de filtrage a été sauvegardé dans l'état applicatif.

**Comment by LGAGELIN** [comment]
Comment sait-on que le paramètre de filtrage a été sauvegardé ? Quand est-il sauvegardé ?

**Comment by Yomguithereal** [comment]
J'ai pushé un fix. Il est pas beau mais il marche.
