### ISSUE TITLE
Insérer en bas de page les documents d'aide

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#352]
Prévoir d'ajouter les documents d'aide dans le footer.
Idée : ajouter  Aide à côté de Gérer vos accès, avec une liste déroulante car il y aura plusieurs documents :
- guide utilisateur
- liste des champs

Ces documents sont en cours d'élaboration. Il faut les stocker comme les mentions légales. Ils doivent s'ouvrir dans un nouvel onglet. 
Les liens seront fournis ultérieurement.

**Comment by LGAGELIN** [comment]
Voici les liens : 
Pour Guide Utilisateur : ​http://www.sciencespo.fr/scpolib/​ISARI/ISARI_Guide_Utilisateur.pdf
Pour Liste des champs :  ​http://www.sciencespo.fr/scpolib/​ISARI/ISARI_Liste_Champs.pdf

**Comment by Yomguithereal** [comment]
J'ai ajouté un menu dans le footer pour cela. Par contre tes liens ne fonctionnent pas et renvoient un 404 #jdçjdr

**Comment by LGAGELIN** [comment]
Bizarre, je regarde avec Grégory

**Comment by LGAGELIN** [comment]
Pour une raison qui m'échappe, es liens sont bidons il y a %E2%80%8BISARI à la place d'ISARI .
Voici les bons liens :
http://www.sciencespo.fr/scpolib/ISARI/ISARI_Guide_Utilisateur.pdf
http://www.sciencespo.fr/scpolib/ISARI/ISARI_Liste_Champs.pdf

**Comment by LGAGELIN** [comment]
Le menu n'est pas visible en PROD ni en PPRD. Dites-moi quand il sera publié

**Comment by LGAGELIN** [comment]
Effectivement les liens ne marchent pas (vu en PPRD)

**Comment by LGAGELIN** [comment]
Corriger sur l'interface en français "help" => "Aide" : 
![image](https://cloud.githubusercontent.com/assets/22589536/23309455/03629c0c-faaf-11e6-8b33-86cc243a90b7.png)
