### ISSUE TITLE
export HCERES - docteurs et doctorants - pb d'exportation des infos de la colonne E

### ISSUE THREAD

**Issue by sophiejacquot** [SciencesPo/isari#354]
Export HCERES, onglet docteurs et doctorants, colonne "établissement ayant délivré le master" = beaucoup de cellules vides dans cette colonne, alors même que les informations correspondantes sont présentes dans ISARI.
Exemple : Département d'économie, Zinedine ALLA 
Dans l'export HCERES contrat en cours, la colonne "établissement ayant délivré le master" est vide pour cette personne. Pourtant, l'info existe dans la fiche de Z. Alla dans ISARI (Ecole polytechnique)

**Comment by paulgirard** [comment]
Le diplôme de ALLA est tagué en "Autre" et non "Master".
Or aujourd'hui je filtre sur master.

J'ai codé une nouvelle règle 
On accepte master ou autre (autrement dit tout ce qui n'est pas HDR et PHD)
On prend le plus récent.

Dites moi si ça vous va sur le principe et je mettrais en pprd

**Comment by sophiejacquot** [comment]
Merci beaucoup Paul oui ça me semble parfait

**Comment by paulgirard** [comment]
ok done
