### ISSUE TITLE
Ajout d'une Activité en tant que Membre, page blanche à la sauvegarde

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#355]
Connectée en tant que membre du CEE (thierry.prieur) sur la PPRD, ajouter une Activité de type projet de recherche. Après la sauvegarde, s'affiche une page blanche, sans tableau. Cela vient du fait qu'aucun labo n'était indiqué dans l'organisation impliquée n'était pas indiquée. C'est logique, mais cela surprend. Ce serait bien d'obliger à saisir au moins une organisation, et d'insister là-dessus en formation.

![image](https://cloud.githubusercontent.com/assets/22589536/23132238/38f79130-f78d-11e6-9739-8b42943ce884.png)

Pourtant l'activité a bien été créée. Cela ne se produit pas en tant qu'admin central (Sophie.jacquot) puisqu'il n'y a pas le problème du rattachement au labo.

**Comment by paulgirard** [comment]
On ajoute l e champs organizations en mandatory pour éviter ce cas;
Même si les utilisateurs peuvent toujours ajouter une orga qui n'est pas leur labo...

**Comment by LGAGELIN** [comment]
C'est dans la v1.02, vu en PPRD
