### ISSUE TITLE
Quand on passe par Autres dans Membres, on perd la persistence des dates du requêteur

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#357]
Cliquer sur Membres, avec une Date de début et une Date de fin.
Cliquer sur Autres
Cliquer sur Activités : les dates du requêteur ne sont plus celles mises initialement. Il n'y a plus de Date de fin, et la Date de début = Date du jour

**Comment by paulgirard** [comment]
La persistence est faite par type d'objet : people, activité, orga.

**Comment by paulgirard** [comment]
erratum : les dates sont globales.

**Comment by LGAGELIN** [comment]
En point d'attention, pour les prochaines séances de  formation, ce comportement se produit uniquement dans 2 cas : 
1/ Si date Début = date du jour . Sinon, la date de début est bien conservée.
2/ Si date Début est vide, alors le système remet l'ancienne date de début
