### ISSUE TITLE
Problème sur le Sans Date pour les Séjours et les Invitations

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#363]
Sur la PPRD, CERI, Activités, ne pas mettre date. Quand on clique sur Toutes les Activités, on a bien les Invitations et les Séjours.
Cliquer sur Invités ou Séjours, le tableau est vide.

Cela ne se produit pas si on met une date, le tableau n'est pas vide; si on va valide une date de début vide, le contenu du tableau s'affiche également.
Même problème que #327 ?

**Comment by paulgirard** [comment]
Le problème est dans el client.
On peut le contourner en vidant explicitement la date de début (même si elle est déjà vide).
Je cherche à le fixer

**Comment by paulgirard** [comment]
Ok donc. Il y a un bug d'affichage.
si on choisit aucune date.
si on passe de toute activité à séjour à l'étranger alors cela revient à recharger la page et donc le comportement classique est de remettre la date de début à aujourd'hui.
Le bug est que la date du jour n'est pas affichée dans le sélecteur mais bien en mémoire.
Ainsi la date de début est affichée à rien mais la requête est elle faite avec la date du jour.

Résoudre le bug est de porté pour moi.
En revanche si on désactive la date du jour par défaut on masque le bug.
Ce peut être une regression intéressante car ça simplifie pas mal l'usage de cette date qui change toute seule.

A discuter.

**Comment by LGAGELIN** [comment]
La date du jour par défaut avait comme utilité de limiter les temps de chargement notamment pour éviter de tout ramener à chaque fois. Prend-on bcp de risques si on l'enlève ?

**Comment by paulgirard** [comment]
Oui c'est vrai que ça peut engendrer plus de charge mais si rien de risqué à mon avis.

**Comment by LGAGELIN** [comment]
OK, suite à ma discussion avec Sophie et à la formation des SG ce matin, nous pensons que la date du jour n'apporte pas vraiment de confort à l'utilisateur, et génère plus d'inconfort comme tu le dis du fait qu'elle change toute seule.  Ce qui est vraiment utile, c'est la persistence des dates saisies par l'utilisateur, et que s'il a viré les 2 dates, il revienne sur des dates vides à la reconnexion.

Du coup, oui, ce serait bien de désactiver la date du jour.

**Comment by paulgirard** [comment]
ok je fais ça.
