### ISSUE TITLE
export HCERES, annexe 4, bug affichage titres d'activités

### ISSUE THREAD

**Issue by sophiejacquot** [SciencesPo/isari#367]
Dans l'export de l'annexe 4, le titre des différentes activités ne s'affiche plus, seuls apparaissent le nom de la personne et la date quand elle existe, alors même que la description de l'activité existe.

Exemple de l'export annexe 4 du CSO : 
Participation à des comités éditoriaux (revues, collections)
    Patrick CASTEL, , depuis 2012
    Christine MUSSELIN, , depuis 1991
    Christine MUSSELIN, , depuis 2008
    Christine MUSSELIN, , 2000 - 2008
    Christine MUSSELIN, , 1999 - 2008
    Christine MUSSELIN, , depuis 2000
    Christine MUSSELIN, , 1999 - 2008
    Daniel BENAMOUZIG,
    Daniel BENAMOUZIG,
 ...

Direction de collections et de séries
    Henri BERGERON, , depuis 2011
    Pierre FRANCOIS,
    Claire LEMERCIER,

etc.

**Comment by paulgirard** [comment]
ok vu et corrigé.
Pour info, c'est du au changement du nom de la variable description dans personalActivities à cause d'un problème technique dont je vous épargne les détails.
