### ISSUE TITLE
export HCERES, annexe 4, bug période temporelle des activités 

### ISSUE THREAD

**Issue by sophiejacquot** [SciencesPo/isari#368]
L'export Annexe 4 remonte des activités qui n'appartiennent pas à la période de l'HCERES (2012-2017).
Exemple annexe 4 du CSO : 
Participation à des instances d’expertises (type Anses) ou de normalisation
    Christine MUSSELIN, , 2007 - 2010
    Daniel BENAMOUZIG, , depuis 2005
    Daniel BENAMOUZIG, , depuis 2007
    Daniel BENAMOUZIG, , depuis 2008
    Daniel BENAMOUZIG,
    Henri BERGERON, , depuis 2011
    Léonie HENAUT,
    Jean-Noël JOUZEL, , 2011 - 2013
    Jean-Noël JOUZEL, , 2009 - 2010
    Emmanuel LAZEGA,
    Emmanuelle MARCHAL-PILLU, , 2003 - 2007
    Emmanuelle MARCHAL-PILLU, , 2009 - 2010

Dans cet exemple, les activités de Christine Musselin, la 2e de JN Jouzel et celles d'Emmanuelle Marchal ne devrait pas apparaitre car elles sont hors du périmètre des dates de l'évaluation

**Comment by LGAGELIN** [comment]
On le savait, on avait dit qu'il valait mieux plus que pas assez...

**Comment by paulgirard** [comment]
J'ai aussi filtré les projets et les distinctions au passage sur le même critère de période HCERES

**Comment by LGAGELIN** [comment]
OK en PPRD . Exemple annexe 4 du CSO :

**Participation à des instances d’expertises (type Anses) ou de normalisation**
Daniel BENAMOUZIG, Membre de la Commission d'évaluation économique et de santé publique auprès du Conseil d'Analyse Stratégique (CAS) et de la Haute Autorité de Santé (HAS), depuis 2005
Daniel BENAMOUZIG, Membre du Comité d'Histoire de la Sécurité sociale, depuis 2007
Daniel BENAMOUZIG, Président du groupe Santé de la Fondation Terra Nova, depuis 2008
Daniel BENAMOUZIG, Animateur du groupe santé de la Fondation Nicolas Hulot
Henri BERGERON, Membre nommé du Comité d'experts auprès du directeur de l'Institut de Santé Publique (IMTO IST INSERM), depuis 2011
Léonie HENAUT, Membre du Comité d'experts "Enquête sur la contribution des services de soins et d'accompagnement mutualistes (SSAM) à la recherche et l'innovation en santé" de la Fondation de l'avenir
Jean-Noël JOUZEL, Membre du groupe de travail "Travailleurs agricoles et pesticides" constitué par l'ANSES, 2011 - 2013
Emmanuel LAZEGA, Membre du Programmatic Steering Board, Hague Institute on the Internationalization of Law
