### ISSUE TITLE
export HCERES, annexe 4, bug ordre alphabétique des activités

### ISSUE THREAD

**Issue by sophiejacquot** [SciencesPo/isari#369]
Dans l'export de l'annexe 4, le classement des activités par ordre alphabétique au sein de chaque catégorie semble un peu capricieux.
Exemple 1 : OSC
Prix
Attribués à des personnes
    Anne-Sophie COUSTEAUX, Médaille de cristal 2015, 2015
    Agnès VAN ZANTEN, Médaille d'argent du CNRS, 2017
    Mathieu D. ICHOU, ECSR Prize for the best PhD thesis
    Juliette N. GALONNIER, Presidential Fellowship
    Lorraine BOZOULS, Bourse Vinci d'aide à la mobilité
    Clémentine L. GAIDE, 1er prix Louis Gruel

Par ailleurs, dans cet exemple, Anne-Sophie Cousteaux ne devraient pas être mentionné dans l'annexe 4 de l'OSC : elle est actuellement membre du CDSP, elle a été membre de l'OSC mais hors période HCERES, de 2004 à 2011 (comme cela est bien à jour dans sa fiche perso).

Exemple 2 : CSO
Christine Musselin vient se placer un peu n'importe où, indépendamment de l'ordre alphabétique, dans chacune des catégories !! : 
- Participation à des comités éditoriaux (revues, collections)
    Patrick CASTEL, , depuis 2012
    Christine MUSSELIN, , depuis 1991
    Christine MUSSELIN, , depuis 2008
    Christine MUSSELIN, , 2000 - 2008
    Christine MUSSELIN, , 1999 - 2008
    Christine MUSSELIN, , depuis 2000
    Christine MUSSELIN, , 1999 - 2008
    Daniel BENAMOUZIG,
    Daniel BENAMOUZIG,
    Daniel BENAMOUZIG,
    Renaud CRESPIN, , depuis 2011
- Responsabilités au sein d’instances d’évaluation
    Christine MUSSELIN, , 2007 - 2010
    Christine MUSSELIN, , depuis 2009
    Christine MUSSELIN, , depuis 2011
    Sophie DUBUISSON-QUELLIER,
- Participation à des instances d’expertises (type Anses) ou de normalisation
    Christine MUSSELIN, , 2007 - 2010
    Daniel BENAMOUZIG, , depuis 2005
    Daniel BENAMOUZIG, , depuis 2007
    Daniel BENAMOUZIG, , depuis 2008
    Daniel BENAMOUZIG,
    Henri BERGERON, , depuis 2011
    Léonie HENAUT,
    Jean-Noël JOUZEL, , 2011 - 2013
- Responsabilités dans des sociétés savantes
    Christine MUSSELIN, 1995 - 2004
    Christine MUSSELIN, depuis 2007
    Christine MUSSELIN, depuis 2007
    Christine MUSSELIN, depuis 2005
    Olivier BORRAZ, depuis 2007
    Didier DEMAZIERE, 2013 - 2015
    Didier DEMAZIERE, depuis 2007
    Emmanuel LAZEGA
    Claire LEMERCIER

**Comment by LGAGELIN** [comment]
Quel niveau de priorité ?

**Comment by sophiejacquot** [comment]
priorité moindre que les titres d'activités, la période et les contrats

**Comment by LGAGELIN** [comment]
OK en PPRD. Exemple :

Participation à des instances d’expertises (type Anses) ou de normalisation

Daniel BENAMOUZIG, Membre de la Commission d'évaluation économique et de santé publique auprès du Conseil d'Analyse Stratégique (CAS) et de la Haute Autorité de Santé (HAS), depuis 2005
Daniel BENAMOUZIG, Membre du Comité d'Histoire de la Sécurité sociale, depuis 2007
Daniel BENAMOUZIG, Président du groupe Santé de la Fondation Terra Nova, depuis 2008
Daniel BENAMOUZIG, Animateur du groupe santé de la Fondation Nicolas Hulot
Henri BERGERON, Membre nommé du Comité d'experts auprès du directeur de l'Institut de Santé Publique (IMTO IST INSERM), depuis 2011
Léonie HENAUT, Membre du Comité d'experts "Enquête sur la contribution des services de soins et d'accompagnement mutualistes (SSAM) à la recherche et l'innovation en santé" de la Fondation de l'avenir
Jean-Noël JOUZEL, Membre du groupe de travail "Travailleurs agricoles et pesticides" constitué par l'ANSES, 2011 - 2013
Emmanuel LAZEGA, Membre du Programmatic Steering Board, Hague Institute on the Internationalization of Law
