### ISSUE TITLE
bug export annex4 si grant sans orga

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#372]
Sur le CERI, export Annexe 4 sort une page d'erreur. 
Le projet Masking Statehood:.... a un grant avec une orga vide.

Si on met une orga sur ce grant, l'export annexe 4 sort bien.

**Comment by LGAGELIN** [comment]
Correction effectuée ce jour : Si un projet n'a pas d'Orga dans son bloc Financement, l'export Annexe 4 sortira sans erreur, le projet sera classé sous la catégorie correspondant au type de financement, et l'orga du financement sera vide.
