### ISSUE TITLE
Membre peut supprimer une Personne

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#373]
Connectée en tant que Alexandre Escudier, j'ai le rôle Membre sur le CEVIPOF.

J'ai cliqué sur Ajouter une Personne, j'ai choisi  Hugo TATEOSSIAN, j'ai cliqué sur le lien. Le bouton Supprimer était visible, actif. J'ai cliqué dessus, la fiche a été supprimée.

Pour info, la personne supprimée était membre de l'école de droit du 20 juin 2016 au 8 juillet 2016.
Après la suppression, la fiche est  introuvable dans la base.

![bouton supprimer](https://cloud.githubusercontent.com/assets/22589536/23549042/9546be36-000a-11e7-9693-d7ef031ce939.png)

![supprression effective](https://cloud.githubusercontent.com/assets/22589536/23549070/b3756718-000a-11e7-9fc6-c45d4ab3751c.png)

**Comment by paulgirard** [comment]
du coup ce qui se passe c'est que la fiche que tu as supprimée est dans le pot commun puisque plus dans le périmètre de l'école de droit.
Du coup il est modifiable par n'importe qui et donc supprimable.
Comportement prévu.

A voir si vous souhaitez modifier le comportement mais ça ne va pas être facile à définir.

**Comment by sophiejacquot** [comment]
J'ai testé la modification/suppression de fiches personnes à partir d'un compte de membre (Nathalie Morel, CEE, LIEPP).
Il est possible de supprimer/modifier la fiche d'une personne qui n'est plus active au sein d'un labo (ex : Matthew Chan, Elisabeth O; De Castex)
Il n'est bien pas possible de supprimer/modifier la fiche d'une personne qui est actuellement membre d'un labo (ex : Patrick Castel)

**Comment by LGAGELIN** [comment]
OK ça s'explique bien effectivement, c'est rassurant... Je propose de ne pas modifier ce comportement, on verra à l'usage si cela pose problème.

**Comment by LGAGELIN** [comment]
Comme vu avec Sophie, on laisse comme ça. Je clos
