### ISSUE TITLE
Export HCERES annexe 4, affichage des contrats = ajouter les dates

### ISSUE THREAD

**Issue by sophiejacquot** [SciencesPo/isari#375]
Dans l'export de l'annexe 4, la liste des contrats apparait, contrairement aux autres activités, sans date. Il serait utile d'ajouter les dates de début et de fin quand on les connaît.

**Comment by LGAGELIN** [comment]
Effectivement, les dates n'étaient pas prévue dans la spéc initiale #219
On peut l'ajouter dans le scope  de la v1.0.4 ?

**Comment by paulgirard** [comment]
oui ok je met ça dans la 1.0.4

**Comment by LGAGELIN** [comment]
Ok en PPRD. Exemple : 
Contrats nationaux (ANR, PHRC, FUI, INCA, etc.)

Go Science (Go Science), Agence Nationale De La Recherche, Jérôme AUST, coordinateur, 01/02/2011 - 31/01/2015
HOWSAFE (HOWSAFE), Agence Nationale De La Recherche, Olivier BORRAZ, coordinateur, 01/01/2013 - 30/06/2016
