### ISSUE TITLE
Suivi de la faculté permanente : enlever l'obligation à remplir le champ à enums

### ISSUE THREAD

**Issue by sophiejacquot** [SciencesPo/isari#380]
Dans le bloc "suivi de la faculté permanente", il est actuellement obligatoire de choisir une des valeurs de l'enum (tenure-track, départ...) pour pouvoir ajouter un commentaire.
Or, ce champ libre de commentaire devrait pouvoir être utilisé sans avoir à compléter nécessairement ce champ "tenure-track, départ". Ce champ libre est en effet le seul espace où indiquer des commentaires de suivi type direction de labo ou de département.
OU ajouter une valeur "autre" dans le champ à enums

**Comment by paulgirard** [comment]
Il nous faut au moins un champs obligatoire dans cet objet sinon on laisse la possibilité de créer des obejts vides... 
Ta solution d'ajouter un enum autre est pas mal. Facile et réponds au besoin.
Je fais ça de suite ?

**Comment by sophiejacquot** [comment]
oui, ce serait bien alors de rajouter une enum "autre" quand tu peux
merci !

**Comment by LGAGELIN** [comment]
OK en PPRD
