### ISSUE TITLE
Bug exports HCERES contrat en cours onglets 2 et 3.2

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#381]
Vu en formation avec SOPHIE;

Pour le CDSP :
l'export HCERES contrat en cours ne fonctionne pas correctement : 
- onglet 2. composition de l'unité : seuls 6 personnes sortent (5+1), alors qu'il y en a 19 dans l'onglet 3.2
- onglet 2. le sous-total des permanents ne se fait pas
- onglet 3.2 : toutes les personnes apparaissent comme "AP_tit" même quand elles sont en CDD

Pour le CERI : 
- idem pour l'onglet 2, pas d'addition des sous-totaux

**Comment by paulgirard** [comment]
pour le 3.2 => changer enum 
  cadre Sciences po en permanent cadre SP
  non cadre Sciences Po en permanent non cadre SP
  non déterminée en non permanent SP

**Comment by paulgirard** [comment]
Bon c'est un mélange de problème de specs (#213) :
J'ai enlevé la contrainte de CDI pour les permanents ministère et CNRS.

et surtout d'un problème des données du labo qui ne sont pas assez précises. Il manque beaucoup de jobType notamment.

J'ai enlevé la contrainte CDD pour les non permanents sciences po.
Mais on a du coup plus de gens que dans le tableau 3.2.
Le 3.2 doit avoir une contrainte différente.
Je n'ai pas le temps d'aller plus loin aujourd'hui.

Le mieux serait de commencer par revoir la spécification #213 et préciser les type de contrats.
Typiquement pour les non permanents il faudrait au moins ajouter les COD ?

Puis de préciser aux labos que les parcours et les jobtype sont importants pour les tutelles FNSP.

**Comment by LGAGELIN** [comment]
Comme vu avec Sophie et précisé par email, pour le tableau 2. Composition de l'unité,  il faut remettre la contrainte CDI et CDD pour les permanents et les non permanents des administratifs et techniques du MESR et CNRS. 

Tu as tout à fait raison, il fallait comprendre que CDD inclut CDD, CDD d'usage, COD, et que CDI inclut emploi public et détachement (pas encore utilisé, mais on le met au cas où). On a mis une nouvelle version de la spéc dans le 213.

Pour l'onglet 3.2, il faut ajouter la contrainte CDD CDI pour affiner les types d'emploi HCERES ,cf issue  #389 .

En effet, il faudra que les jobType soient saisis pour toutes les tutelles. On fera une communication aux centres pour leur expliquer.

**Comment by paulgirard** [comment]
Pour la question du temporaire/permanent.
Pour tous les personnels académiques la définition de temporaire ou permanent dépends du grade tel que défini dans https://github.com/SciencesPo/isari/blob/master/specs/export/grades2gradesHCERES.json
Pour les personnels administratif et technique on utilise le jobType pour définir si elle/il est permanent : 
      - CDD, stage, alternance, COD, CDDdusage
      - CDI, disponibilité, détachement, emploipublic
      - valeur vide => on ne classe pas la personne, la colonne e serait vide dans 3.2 pour indiquer le problème

A faire : 
- [ ] calculer les totaux et sous-totaux dans l'onglet 2
- [ ] onglet 2, il faut réutiliser la traduction des grades faits pour l'onglet 3.2 pour déterminer si les personnels académiques sont permaments ou temporaires
- [ ] onglet 2 et 3.2 il faut déterminer le "Type d'emplois" (3.2) et le caractère permanent ou temporaires (2) des admin et tech en fonction du jobType. On ne remplit pas la case et on ne compte pas si le jobType est vide.
- [ ] comme on utilise le jobType et non le grade pour temporaire/permanent des personnels admin tech on revient sur notre décision de renommer les grades Sciences Po en ajoutant permanent et temporaire.
- [ ] on supprime le grade temporaire sciences po et on bascule les personnes ayant ce grade en "grade sciences po"
