### ISSUE TITLE
Eviter la page blanche lorsqu'on accède à une  Activité d'un autre labo

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#383]
Amélioration demandée par les utilisateurs : lorsqu'on accède par un lien à une activité qui n'est pas du labo dans lequel on se trouve, la  page s'ouvre, mais elle est blanche. C'est un peu surprenant et cela donne à pense que l'outil ne fonctionne pas.
Propositions : 
1/ mettre un feedback plutôt que d'ouvrir la page blanche, genre " cette activité est rattachée à un autre centre de recherche".
2/ laisser la consultation possible, mais sans possibilité d'éditer.

La 1/ est plus conforme à la spéc. mais c'e n'est pas cohérent pour l'utilisateur avec le système des Personnes, qu'il peut consulter tout le temps.

**Comment by LGAGELIN** [comment]
Se produit avec les 3 rôles : membre du centre, éditeur de centre et admin de centre.

**Comment by LGAGELIN** [comment]
Sur la version actuelle de PPRD, le système indique "page not found ". Il faudrait le remplacer par exemple, par : "Cette activité est rattachée à un autre centre".
![image](https://user-images.githubusercontent.com/22589536/30795976-62fa2a22-a1d0-11e7-8f1f-63a993b13f57.png)

**Comment by paulgirard** [comment]
même bug que #476
