### ISSUE TITLE
compléter l'export HCERES - contrat en cours - onglet 3.3 - docteurs et doctorants

### ISSUE THREAD

**Issue by sophiejacquot** [SciencesPo/isari#384]
Actuellement, il reste une colonne de l'onglet 3.3 pour laquelle aucune information n'est exportée depuis ISARI : la colonne I "Financement du doctorant (4)".
Ces informations vont être saisies à la main dans ISARI, dans le champ "instrument de financement" (avec un type de financement = doctorat).
Cependant, il faudrait que l'export fasse la traduction de la liste de valeurs "instrument de financement", qui est celle du référentiel des financements de thèse de Banner, vers le référentiel HCERES, dont les codes doivent apparaitre dans l'onglet 3.3.
La table de correspondance entre les financements Banner et les financements HCERES se trouve dans le document ici : https://docs.google.com/a/sciencespo.fr/spreadsheets/d/1kq4hLRoBRyiyuUJdTlmS63IGnUzNqgE0_75xEG4Zkr4/edit?usp=sharing

**Comment by LGAGELIN** [comment]
Il faudra voir avec Paul la faisabilité et le délai de réalisation.

**Comment by paulgirard** [comment]
On attend que des exemples de données soient rentrées pour permettre de tester.

**Comment by paulgirard** [comment]
ok pour l'école de droit. A prévoir pour la 1.0.6

**Comment by paulgirard** [comment]
On n'export que les codes séparés par des virgules si il y en a plusieurs.
