### ISSUE TITLE
Annexe 4 - filtre Activités suivant affiliation

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#387]
Par ailleurs, dans cet exemple, Anne-Sophie Cousteaux ne devraient pas être mentionné dans l'annexe 4 de l'OSC : elle est actuellement membre du CDSP, elle a été membre de l'OSC mais hors période HCERES, de 2004 à 2011 (comme cela est bien à jour dans sa fiche perso).

**Comment by LGAGELIN** [comment]
OK en PPRD : 

Sur Export Annexe 4, au niveau de 8. Indices de reconnaissance / Prix / Attribués à des personnes :

**CSO **, Anne-Sophie Cousteaux n'y est plus  :+1: 

Lorraine BOZOULS, Bourse Vinci d'aide à la mobilité
Clémentine L. GAIDE, 1er prix Louis Gruel
Juliette N. GALONNIER, Presidential Fellowship
Mathieu D. ICHOU, ECSR Prize for the best PhD thesis
Agnès VAN ZANTEN, Médaille d'argent du CNRS, 2017

**CDSP**  : Anne-Sophie Cousteaux apparapit bien :+1: 

Anne CORNILLEAU, Médaille de cristal 2015, 2015
Anne-Sophie COUSTEAUX, Médaille de cristal 2015, 2015
Geneviève MICHAUD, Médaille de cristal 2015, 2015
