### ISSUE TITLE
Tableau HCERES 3.2 Liste des personnels : Affiner les règles du Type d'emploi HCERES

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#389]
Il faudrait ajouter une contrainte sur le jobType pour déterminer le type d'emploi HCERES :
- permanent = CDI ou emploi Public
- non permanent = CDD

Il faudrait documenter les règles actuelles de transformation en type d'emploi HCERES.

**Comment by LGAGELIN** [comment]
#381

**Comment by paulgirard** [comment]
duplicates #381
