### ISSUE TITLE
annexe 4, contrats : il faudrait filtrer sur les contrat avec un financement dont le statut est "accepté" ou "en cours" uniquement, 

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#395]
car actuellement tous les contrats ressortent, y compris des projets qui viennent juste d'être soumis et dont on ne sait pas encore s'ils ont été accepté ou non (ex : CHSP, contrat ANR Envirofrontiers)

**Comment by LGAGELIN** [comment]
Ok en PPRD, les Soumis ou Non retenu ne sortent pas dans l'annexe 4. On n'a bien que les Accepté et En cours
