### ISSUE TITLE
Requêteur de date sur les Activités fonctionne mal (ne filtre pas toujours)

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#398]
Si on indique une date de début seulement dans le requêteur du tableau Activités, le système ne filtre pas correctement. Il affiche des lignes hors période, par exemple des activités terminées avant la date.

Si on met 2 dates dans le requêteur, en revanche ça fonctionne très bien. 

Le comportement est bizarre, car dès qu'on a commencé à mettre 2 dates, puis qu'on en supprime une, ça marche bien

**Comment by paulgirard** [comment]
Vérifier le bug à mon avis ça n'arrive que quand on charge la page la première fois.
Ça vient sans doute du système de sauvegarde de la date de filtrage dans le local storage.

**Comment by LGAGELIN** [comment]
Il faudrait refaire le test ensemble car j'ai obtenu des choses différentes et qui paraissent incohérentes.

Voici ce que j'ai fait sous Firefox :
Vider le cache du navigateur. Se connecter avec olivier.borraz, Aller sur Membres, constater qu'il n'y a aucune date dans le requêteur. Renseigner une date de début (2000), celle-ci est bien prise en compte dans le filtrage des Membres. Ouvrir les Activités=> la date de début n'est pas appliquée dans le filtrage du tableau, des activités hors période apparaissent.
Après la déconnexion/reconnexion, la date de début n'est pas affichée, non plus. Je la remets dans Membres, ça filtre, mais dans Activités elle n'est pas appliquée dans le filtrage.
J'ai également observé qu'après avoir mis une date de fin, la date dé début n'était plus présente à la reconnexion suivante.

Il faudrait savoir comment ces dates sont enregistrées dans LocalStorage, et en quoi les paramètres du navigateur influent ce stockage.

**Comment by LGAGELIN** [comment]
Autre exemple :
Logée en tant qu'admin central :

je suis sur le CEE avec 2 dates 1/01/2015 au 31/12/2015 et ça marche très bien
J'ai aussi tenté le CDSP, nickel.
J'ai aussi tenté une seule date : 2015, et ça marche aussi.

en revanche,  je change de labo, je passe au CSO sur les membres et là la date change , elle passe à 2009. Je passe aux Activités, la date est toujours à 2009, mais les données affichées ne sont pas filtrés. J'ai des données 2013-2020, ou 2015
Images intégrées 1
