### ISSUE TITLE
Non prise en compte de la suppression de startDate et endDate dans les Activités

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#403]
Il est impossible de supprimer les startDate et endDate d'une activité,  sur les projets, les doctorats,, etc.... c'est le même comportement. Le système indique Save Success, mais il n'a pas pris en compte la suppression. Les dates sont toujours là. En revanche, si on les remplace, celles-ci sont bien prises en compte. ça  le fait sous Chrome, Firefox. Pourtant les dates ne sont pas obligatoires.

**Comment by t8g** [comment]
Ping @Yomguithereal 

Ça viendrait pas de là

https://github.com/SciencesPo/isari/blob/master/server/lib/rest-utils.js#L224

Et en fait du coup c'est pareil avec tous les champs de 1er niveau ...


Filé dans le PUT
```json
{
  "id": "58f731b2a00a770001e3b95c",
  "diff": [
    {
      "type": "update",
      "path": [
        "birthDate"
      ],
      "value": ""
    }
  ]
}
```
La clé birthDate est virée de l'objet ici
https://github.com/SciencesPo/isari/blob/master/server/lib/rest-utils.js#L200
Et remise ici
https://github.com/SciencesPo/isari/blob/master/server/lib/rest-utils.js#L224

Qu'en penses-tu ?

**Comment by Yomguithereal** [comment]
Ca a l'air d'être ça, oui. J'ai l'impression que mon algo pourrave ne gère pas la deletion des champs de premier niveau comme tu le dis.

**Comment by t8g** [comment]
t'as une idée ? On est parti sur du crado, mais si t'as mieux ...

**Comment by Yomguithereal** [comment]
Il faut faire pareil que pour l'update nesté. Gérer cette opération dans le client => go server et supprimer le champ du document. Pas d'autre solution.

**Comment by t8g** [comment]
On a fait

`setIn(updated, operation.path, 'TO.BE.REMOVED')` à la place du `unset`
et `if (updated[f] === 'TO.BE.REMOVED') doc.set(f, undefined, {strict: false} )`

Mais on a eu un pb sur les date (sur lesquels un set est défini qui n'accepte pas undefined).

Bon ça marche je commite et tu me diras ...
