### ISSUE TITLE
séparé faculté temporaire de permanente dans un autre onglet

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#405]
un nouvel onglet 
faculté temporaire : 
- émérite ...*
- Postdoc
- CASSIST
- doctorant
- invité 
- contractuel
- ater
- doctorant
- invité
les grades du statut enseignant

On enlève les temporaires de l'onglet permanent

**Comment by LGAGELIN** [comment]
Quelle est la règle implémentée sur les grades et statuts ?
Est-ce qu'on regarde uniquement les statuts Chercheur et Enseignant ? Ou bien on regarde les grades listés indépendamment du statut ? Je pense notamment au cas des Invités et les Doctorants, qui se trouvent potentiellement dans différents statuts (chercheurs, enseignants chercheurs, chercheur enseignant, enseignant). Est-ce qu'on prend que ceux de Chercheur ou tous ?

**Comment by paulgirard** [comment]
est défini comme faculté permanente : 
gradeStatus NOT IN [ 'appuiadministratif', 'appuitechnique', 'enseignant']
ET grade NOT IN ['directeurderechercheremerite','cherchcontractuel','postdoc','invité','CASSIST','doctorant(grade)','profémérite','profunivémérite','enseicherchcontractuel','ater']

faculté temporaire: 
gradeStatus NOT IN [ 'appuiadministratif', 'appuitechnique']
ET grade NOT IN grade permanents

**Comment by LGAGELIN** [comment]
Donc les grades **Chargé d'études** et **Directeur d'études** sont de la faculté permanente.
Sophie, pourrais-tu confirmer stp ?

**Comment by LGAGELIN** [comment]
Autre question : Les Invités sont dans la faculté TEmporaire, mais on les veut quand même dans un onglet à part. Est-ce normal ?

**Comment by LGAGELIN** [comment]
Paul, on est d'accord que les grades "Invités" sont exclus de l'onglet "Faculté Temporaire" ?
