### ISSUE TITLE
ajouter un scroll sur les suggestions

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#409]
Les suggestions sur enum liste les possibilités mais de manière non exhaustive.
L'ordre dépends de ce qui a été ajouté à l'input texte.
Le problème est que dans le cas de longue liste, les utilisateurs n'ont pas idée de ce qui existe, ne voit pas tous les cas et ne peuvent pas les voir apparaître... 
Ajouter un scroll suffirait.

**Comment by t8g** [comment]
Fixed by https://github.com/SciencesPo/isari/commit/3b9d17c2f32c41a480f6cafc7345dff9a6fbfefd
