### ISSUE TITLE
Ajouts et mise à jour formulaire Activités

### ISSUE THREAD

**Issue by sophiejacquot** [SciencesPo/isari#417]
Ajouts d'enums dans des listes de valeurs : 
- Personnes impliquées > rôle = ajouter le rôle "Project manager"
- Organisations impliquées > rôle = ajouter le rôle "Partie tierce"
- Financement > Statut = ajouter le statut "Terminé"

Ajouts de champs dans le bloc Financement (avec sortie dans les colonnes du tableau): 
- ajouter un champ libre "Commentaires"
- ajouter un champ date "Date signature convention"

**Comment by paulgirard** [comment]
"Partie tierce" et organisation sans rôle spécifique c'est un peu la même chose non ?
Quoiqu'il en soit je l'ai ajouté.
