### ISSUE TITLE
petits changements dans l'interface

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#430]
- [x] Add name field from valueBefore in editlog table when edit type  = delete
- [x] remove duplicates in fields column cells
- [x] mettre un message quand l'api renvoie rien
- [x] enlever le lien sur les organisation
- [x] bug bouton lien rouge dans input people

**Comment by t8g** [comment]
Pour le type delete y'a déjà les clés il me semble, puisqu'on a un path. En tout cas j'ai bien des infos qui s'affichent. 
@paulgirard peux-tu confirmer ?

**Comment by paulgirard** [comment]
Les edits de type delete n'affichent aucune info dans itemName.
Or on a le champs name dans la value after.

MMM Je te le fais côté serveur.

![image](https://user-images.githubusercontent.com/193478/30018484-5235ae2e-915d-11e7-9ae7-9843c5cb1c92.png)

**Comment by paulgirard** [comment]
Fixé côté serveur.
En revanche cela produit des liens vers des objets supprimés.
Donc
- [ ] ne pas mettre de lien sur le itemName si edit.type = delete
- [ ] afficher un message quand l'editor tombe sur un 404 : 
http://localhost:4200/people/(editor:59381e519d1afc00015fd592)?organization=

**Comment by t8g** [comment]
Ah oui j'étais pas réveillé j'ai confondu field / item
Sorry
