### ISSUE TITLE
 télécharger une page dans un tableau en XLS

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#437]

**Comment by t8g** [comment]
**En mode non détaillé**

1 ligne = 1 editLog
Colonnes = date / item / action de l'editLog / champs modifiés / auteur / labo auteur / rôle auteur

**En mode détaillé**

1 ligne = 1 diff
Colonnes = date / item / action du diff / champ / valeur avant / valeur après / auteur / labo auteur / rôle auteur

**Comment by t8g** [comment]
[ ] csv sans détail
[ ] csv détaillé
[ ] xls sans détail (?)
[ ] xls détaillé
