### ISSUE TITLE
impossibilité d'accès à certains champs pour le rôle "éditeur du centre"

### ISSUE THREAD

**Issue by sophiejacquot** [SciencesPo/isari#442]
Problème apparu post-migration annuaire : 2 personnes ayant un rôle "éditeur du centre" ne peuvent agir sur certains champs qu'elles devraient pourtant pouvoir éditer (grade/n°ORCID), le champ est grisé et inactif.
C'est seulement après plusieurs manipulations (ouverture/fermeture de l'appli, suppression/création du bloc concerné) que la possibilité d'agir sur le champ est de nouveau possible

**Comment by LGAGELIN** [comment]
L'une des personnes était Silvia duerich-morandi et a finalement réussi à modifier.
