### ISSUE TITLE
Règles d'accès tableau editLog global

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#445]
l'EditLog central est l'editlog non lia à un objet particulier de la base.
Ce dernier doit avoir un accès réservé :

- [ ] Le bouton d'accès Editlog doit être réservé à central_admin, central_reader et center_admin
- [ ] le client doit afficher un message "vous n'avez pas le droit" si il reçoit un 401

**Comment by paulgirard** [comment]
question @LGAGELIN @sophiejacquot : 
Est ce qu'on ne donnerait pas accès au tableau d'edit aux admin des centres ?

**Comment by LGAGELIN** [comment]
Oui bonne idée. On a vu que c'était déjà le cas en PPRD, c'est très bien (à part que cela ne fonctionne pas ;-) cf issue 451)

**Comment by paulgirard** [comment]
central_admin : paul.girard
central_reader : charline.avenel
center_admin : barbara.bender

**Comment by t8g** [comment]
Pour un center_admin 
Je devrais avoir accès aux logs, non ?
http://localhost:8080/editLog/people?organization=5894889a11d0d100381bcc9c&limit=5
Me donne 401 pour barbara.bender
```
{ isariRole: "center_admin", organization: "5894889a11d0d100381bcc9c" }
```

**Comment by paulgirard** [comment]
Il faut changer la règle côté serveur.
C'est un changement de specs.

**Comment by t8g** [comment]
Du coup pas compris.
On fait ou pas ?
