### ISSUE TITLE
Ne pas prioriser who sur shoRole et whoOrganization

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#447]
Si dans les filtres Modifié par et Organisation, on met des infos incohérentes (ex : Paul Girard, CEE), le système ne devrait rien retourner.

**Comment by paulgirard** [comment]
plus précisément les filtres impactés sont : 
- who 
- whoRole
- whoOrganization

Aujourd'hui si il y a un filtre who le serveur ignore les deux autres.

Ce qui est souhaité c'est de ne pas prioriser et de laisser la requête se faire complètement avec les différents filtres même si incohérent.

En cas d'incohérence l'API ne renvoie aucun edit et le client prévient l'utilisateur que c'est vide.
Comportement ok.

L'utilisateur doit apprendre à filtrer correctement. One fait pas de magie pour lui.
