### ISSUE TITLE
Régression : filtrage du scope empêche de récupérer les action=delete 

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#448]
Si l'on demande à l'API les edits de type delete sur un scope d'organisation.
L'algo actuel fait : 
- quels sont les objets du périmètres
- quelles sont les edits de type delete qui concernent un des objets du périmètre

=> Les objets qui ont subi un delete ne sont par définition plus dans la mongo et donc ne sont pas retourné par la requête de détermination des objets du périmètres.

Les actions delete ne sont donc jamais retourné à cause du scope.

La requête de filtrage du scope devrait donc être appliquée non pas en amont mais pendant la requête sur la collection de l'editlog sur l'objet data pour les cas d'edit delete.

Gros refacto à prévoir.

**Comment by naholyr** [comment]
Ça devrait être OK

**Comment by paulgirard** [comment]
- [ ] switcher de who à  whoID dans le middleware en cas de création/suppression
- [ ] suppression d'un objet n'apparaît pas dans l'editlog
