### ISSUE TITLE
Bug affichage des difs : scalaire considéré comme Array

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#449]
Des valeurs scalaires sont affichées comme des arrays.
Régression suite à la gestion des valeurs contenant des array je pense.

A étudier et corriger en espérant que ce soit bien qu'une régression côté client

**Comment by LGAGELIN** [comment]
Nous confirmons le problème des enums ;-)
![image](https://user-images.githubusercontent.com/22589536/30273960-98304576-96fb-11e7-98fd-329fffed6ed7.png)

**Comment by paulgirard** [comment]
il y a donc aussi un bug introduit lors de la gestion des valuers de type array apparemment

**Comment by paulgirard** [comment]
je met le problème des enums dans une autre issue

**Comment by t8g** [comment]
Je dirais que c'est un pb server
![image](https://user-images.githubusercontent.com/639759/30796542-cfc69b98-a1d2-11e7-9e1b-05a9f2166cd5.png)

Je regarde ça avec @naholyr

**Comment by t8g** [comment]
J'espère surtout que c'est un pb de rendu des données et pas de stockage. Je regarde dans la base.

**Comment by t8g** [comment]
Aïe ...
![image](https://user-images.githubusercontent.com/639759/30796690-73e57a3c-a1d3-11e7-8ad1-4687b5085c52.png)

Là on est passé de FR (France) à AU (Australie) et on voit bien qu'on a stocké "F" -> "A" et "R" -> "U"

Comment on fait @paulgirard ?
