### ISSUE TITLE
DUPLICATE #449 Toutes les valeurs ne sont pas lisibles dans le détail des modifications

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#450]
Exemple sur la fiche de Stéphane LATTE ABDALLAH (CERI) : 
- on ne peut pas lire quelle organisation a été créée : 2 champs s'affichent ref et value, et on ne donnent pas le nom de l'orga , 
- on ne voit pas quel pays a été renseigné  : 2 lignes s'affichent 0, et 1 avec chacune une lettre, alors que le pays renseigné est France. 

![image](https://user-images.githubusercontent.com/22589536/30261777-73091656-96ce-11e7-8cb7-9403e6f78971.png)

![image](https://user-images.githubusercontent.com/22589536/30261909-f810c484-96ce-11e7-9326-8f2ca8abf43f.png)

**Comment by paulgirard** [comment]
Duplicates #449

**Comment by paulgirard** [comment]
Je laisse pour vérification suite à la #449

**Comment by naholyr** [comment]
* Problème des chaines adressé dans la #449 
* Problème des IDs invalides sera adressée dans la #462
