### ISSUE TITLE
Avec un rôle autre que Admin Central,  impossible d'accéder au tableau Editlog global

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#451]
Quand on clique sur le bouton EditLog, depuis un centre, en sélectionnant Membres (par exemple), ça mouline dans le vide.

Pour tester :
- avec le rôle DG, utiliser le compte anita.beldimanmoore, mode de passe MigrationLDAP2017
- avec le rôle Editeur Centre : sylvie.lesur (mode de passe MigrationLDAP2017)
- rôle Membre : anne.revillard (toujours le même mot de passe)

**Comment by paulgirard** [comment]
c'est normal.
La protection a été faire côté serveur mais pas côté client voir mon commentaire à propos de la gestion de l'erreur 401  #445 
Je clos
