### ISSUE TITLE
Perte d'info lors de  l'ajout d'un bloc Diplôme supplémentaire

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#453]
Un diplôme existe.
Cliquer sur Ajouter Diplôme. Sélectionner le type de distinction => Le Type de diplôme du bloc Diplôme existant se vide.
Exemple sur la  fiche de Stéphanie LATTE

![image](https://user-images.githubusercontent.com/22589536/30272396-9ef2bc88-96f4-11e7-943f-f4242aa69f3e.png)

**Comment by paulgirard** [comment]
Régression.
On ne peut plus ajouter de nested enums du tout !
