### ISSUE TITLE
duplicate #449 ? Ajout de Nationalité : édition ou création ?

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#454]
Lorsqu'on ajoute une Nationalité alors qu'une existait déjà, le système présente : 2 Acctions d'édition et une Création.
Ne devrait-on pas avoir une Edition Seulement ?
Par ailleurs, les contenus de la modification ne sont pas lisibles :

![image](https://user-images.githubusercontent.com/22589536/30272632-b474426a-96f5-11e7-8db3-21996eaf6af9.png)

**Comment by paulgirard** [comment]
mmm étrange peut être un bug d'affichage lié à #449

**Comment by naholyr** [comment]
Je confirme que c'était un effet de #449, le résultat de cette opération maintenant sera plutôt ainsi :

```diff
- FR
+ AD
+ FR
```
