### ISSUE TITLE
Manque un export des logs au format Excel

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#455]
Pour les utilisateurs, il est préférable qu'il n'aient pas à convertir les données .csv, d'autant que la conversion n'a pas permis de remettre les valeurs dans les bonnes cases.

EN plus, avant la conversion : on voit un décalage dans les infos qui explique peut-être l'issue 458

![image](https://user-images.githubusercontent.com/22589536/30275015-1186d684-9700-11e7-8097-b9bdaf02dde7.png)

**Comment by paulgirard** [comment]
duplicates #437 
Merci de lire les autre issues avant d'en déposer de nouvelles ça fait perdre du temps à tout le monde.
