### ISSUE TITLE
Ajouter un compteur de résultats dans le tableau EditLogs

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#457]
A l'heure actuelle, le nombre de résultats max par page est pratique. Il manque cependant le nombre de résultats retournés. Cela est d'autant plus utile quand on exporte le tableau.

**Comment by paulgirard** [comment]
Oui faisable on a même une route d'API faite pour autre chose d'hoorible que l'on a dieu merci virer qui sera très pratique pour ça. 
ps @t8g : peut être est ce possible (ce serait plus efficace) de chercher à avoir le nb de résultat en une seule requête en complément des données paginées. à étudier.

**Comment by naholyr** [comment]
En une seule requête mongo ce n'était pas possible, mais j'ai du coup injecté systématiquement le nb de résultats dans l'API, on passe donc de `[…]` à `{count: …, logs: […]}` en réponse. J'ai inclus l'information entre les flêches de pagination, à peaufiner.
![image](https://user-images.githubusercontent.com/214067/30813653-4cf5a240-a20e-11e7-8598-e83833b71ddd.png)
