### ISSUE TITLE
résolution des enums des organisations et activités

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#467]
![image](https://user-images.githubusercontent.com/193478/30965394-97ef5040-a455-11e7-916c-8aa562d87b45.png)

![image](https://user-images.githubusercontent.com/193478/30965578-222e1570-a456-11e7-8144-35427253be3e.png)

Le problème est présent dans tous les types d'edit creation update deletion

**Comment by t8g** [comment]
Bon en fait c'est les enuls en gal qui n'étaient pas gérés.
