### ISSUE TITLE
Ne pas afficher le bouton Editlog pour le rôle CentralReader

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#472]
Pour le rôle Central Reader : Inutile de présenter le bouton EditLog dans les Tableaux

**Comment by paulgirard** [comment]
bouton editlog dans le menu ne doit pas s'afficher pour le role central_reader

**Comment by paulgirard** [comment]
le center_admin n'a plus accès !

**Comment by t8g** [comment]
T'as vu la modif ?
Je vois pas comment ça peut être lié.
Pas plutôt un pb back ?

**Comment by t8g** [comment]
Je testerai ça demain.

**Comment by paulgirard** [comment]
Je n'ai pas regardé encore...

**Comment by paulgirard** [comment]
je dois pouvoir gérer ça
