### ISSUE TITLE
Régression Problème dans la navigation d'une fiche vers un tableau

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#474]
Dans Membres, ouvrir une fiche People, aller dans Activités => message d’erreur apparaît
![image](https://user-images.githubusercontent.com/22589536/31082459-60e75632-a78f-11e7-9f62-dbc95664fc2f.png)

Puis ça mouline dans le vide. Recharger la page permet d'arrêter le cycle.

**Comment by paulgirard** [comment]
D'après le message d'erreur le passage du formulaire people à activities a été fait par un lien d'un champs ForeignKey non ? auquel cas c'est le même bug que #476

**Comment by t8g** [comment]
Corrigé : il manquait un unsubscribe
