### ISSUE TITLE
Bug gestion des droits/scope orga quand champ Date de fin de rattachement labo au format AAAA 

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#475]
Dans le cas d'une date de fin de rattachement de labo = 2017, le système semble l'interpréter comme 1/01/2017 au lieu de 31/12/2017. 
Cette anomalie donne le droit d'éditer une fiche Membre alors que la personne est encore rattachée à un autre labo. Si on met 2018, la fiche n'est plus éditable.

**Comment by paulgirard** [comment]
Après vérification le problème est côté serveur.

**Comment by paulgirard** [comment]
J'ai corrigé.
La personne est bien en lecture seule si sa date de fin est en 2017.

Petite interrogation fonctionnelle cela dit.

Dans le cas des activités, si l'activité est dans un autre scope on n'affiche qu'un message d'erreur et on ne permet pas à l'utilisateur de voir la fiche.

Dans le cas des peoples, si la personne n'est pas dans un autre scope on n'affiche la personne en lecture seule.

Ce n'est pas cohérent.
