### ISSUE TITLE
Message d'erreur et bug lors de l'accès à une activité d'un autre labo

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#476]
En tant qu'éditeur de centre ou membre, via le bouton ajouter une Activité , sélectionner un projet qui n'est pas du labo courant. Un message d'erreur s'affiche, puis ça mouline . Même en rafraichissant la page, on ne revient pas à la normale

**Comment by paulgirard** [comment]
- [ ] mettre label message 403 dans i18n
- [ ] virer le loadder en cas d'erreur et afficher le message
- [ ] vérifier le comportement souhaité côté serveur

**Comment by LGAGELIN** [comment]
Il reste à modifier le message qui s'affiche => "Vous n'avez pas accès à cette information" plutôt que "Vous n'avez pas le droit d’accéder à cette information."
