### ISSUE TITLE
Séparateurs de champs retour-chariot dans les exports xls

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#479]
Dans l'export des logs au format .xls, en ayant ouvert le fichier avec Excel , quand on n'est pas en mode détail, au niveau de la colonne champs modifiés, on a des trucs bizarres, pas très lisibles en particulier pour les champs qui sont à la racine dans le modèle et qui ont été mis à jour dans une même session.
ça donne ça :
Images intégrées 1
![image](https://user-images.githubusercontent.com/22589536/31331144-8b52a190-ace1-11e7-8fcb-d57d02b0f313.png)

​Si on ​fait un ​"​Renvoi à la ligne pour cette colonne​"​, les infos sont affichées en ligne dans la même cellule. En revanche, on ne peut pas filtrer sur les items de la liste.
​
​Quand on exporte le même fichier au format csv, sans le mode Détails,  que faut-il indiquer comme séparateur pour les champs modifiés ?
Images intégrées 2
![image](https://user-images.githubusercontent.com/22589536/31331121-7ff4c116-ace1-11e7-9d9d-0d4765e9ad7d.png)

​

**Comment by paulgirard** [comment]
![image](https://user-images.githubusercontent.com/193478/31495983-ef1b3c44-af59-11e7-821c-da53abb7e2e3.png)

Le problème est : 
les retours-chariots sont absents de l'export XLSX
