### ISSUE TITLE
interactions formulaire/tableau

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#48]
Dans le tableau:
- remplacer les boutons par l'action de click sur les lignes du tableau
- ajouter un style sur la ligne sélectionnée: genre assombrir le fond  
- provoquer un scroll et mettre le focus sur le formulaire

**Comment by paulgirard** [comment]
que se passe t'il quand tu changes de pages ou de clef de trie ?

**Comment by paulgirard** [comment]
on oublie l'idée des boutons privous next.
Pas si utile pour le métier et relou pour le design interactif

**Comment by t8g** [comment]
Ça doit être bon
