### ISSUE TITLE
Instabilité dans l'affichage de la colonne Organisation des éditeurs de la donnée

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#482]
Dans les tableaux Historiques, la colonne Organisation des personnes (isariLab) qui ont modifié la donnée est parfois vide.
Elle se remplit après un refresh de la page dans les tableaux Historiques globaux (mais pas dans l'historique au niveau d'une fiche)

**Comment by paulgirard** [comment]
régression suite à #292 
Le cas problématique implique un appel à l'api string avec pas assez d'ids dans la query.
Si on recharge l'appel à cette api depuis le client est correcte et tout se passe bien.

La détection des FK dans les données de l'editlog est donc parfois cassé.
J'ai l'impression qu'elle est cassée quand on passe par un formulaire (qui utiliser aussi l'api string).

A étudier

**Comment by paulgirard** [comment]
Pas facile à reproduire mais j'ai réussi à isoler un cas (sans doute pas le seul).
Se connecter en tant que central admin (paul.girard)
Aller dans médialab / membres
Ouvrir une fiche people.
Ouvrir EditLog / oorganisation

> la colonne Organisation est vide.

Recharger la page : la colonne est remplie.

**Comment by t8g** [comment]
Ok je reproduis
Je regarde tout de suite

**Comment by LGAGELIN** [comment]
Sur la version du 6 nov 217, je tombe de temps à autre sur une colonne vide, mais je n'arrive pas à reproduire systématiquement....
![image](https://user-images.githubusercontent.com/22589536/32717743-1a2a2f66-c85b-11e7-8961-4236540dfe55.png)

**Comment by paulgirard** [comment]
je n'arrive pas à reproduire... 
Ça ressemble à une requête qui va chercher les labels des organisations qui se termine mal mais rarement. Genre perturbations réseaux ?

je propose de fermer ?

**Comment by paulgirard** [comment]
peut être liée à #491

**Comment by paulgirard** [comment]
vue la résolution de #491 je pense que c'était le même problème. je clos
