### ISSUE TITLE
"Ref not found" dans l'historique sur les modifications d'organisations

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#483]
Lorsqu'on ajoute/supprime une organisation dans un Membre ou Activité, l'historique ne logge pas la valeur de l'organisation ajoutée ou modifiée. Le système indique ref. not found

![image](https://user-images.githubusercontent.com/22589536/31621011-00940446-b299-11e7-95ad-cedae992e804.png)

**Comment by paulgirard** [comment]
Peut être le même problème que #482 
Les données renvoyées par le serveur sont correctes.
Problème semble lié non pas à la détection des FK mais à leur résolution.

**Comment by paulgirard** [comment]
Pour répliquer : 
- ouvrir une personne avec un diplôme (adrien fauve au médialab par exemple).
- changer l'organisation d'un de ses diplômes (remplacer Sciences Po par EHESS)
- sauvegarder
- ouvrir l'historique dans la fiche

L'edit log affiche correctement Sciences Po mais pas EHESS (ref. not found)
![image](https://user-images.githubusercontent.com/193478/31708579-afc35424-b3ef-11e7-95f1-8d3bad69aaf3.png)
Pourtant les données de l'api semblent être correctes
![image](https://user-images.githubusercontent.com/193478/31708610-c5b574f6-b3ef-11e7-918c-8c02ca93f558.png)

Les FK dans valueAfter semblent en pas être résolues correctement ?

**Comment by LGAGELIN** [comment]
J'ai rouvert l'issue car j'ai eu le souci sur la fiche de Bismuth, j'ai fait des modifs sur la Tutelle dans Parcours, j'ai ajouté un bloc avc une Tutelle, et j'ai modifié une tutelle existante. Or les modif dans l'historique de la fiche n'étaient pas visibles alors que les sessions d'enregistrement étaient bien présentées . La tutelle ne s'affichait pas, ou bien il y avait Ref not found. Mais la situation s'est rétablie quelques minutes après, les données que j'avais créées sont bien affichées, et les valeurs avant/après de la tutelle modifiée aussi. On peut supposer que c'est lié à un délai de mise à jour. Pouvez-vous m'éclairer ?

**Comment by paulgirard** [comment]
Première explication de 'ref. not found'
On a modifié l'enums grades pour virer le grade temporaire : 
https://github.com/SciencesPo/isari/commit/b59cbecbff233aec92a7f2e54d4e1fa0f231faf1

On a bien veiller à supprimer cette valeur d'enum des objets.
Oui mais ces valeurs sont restées dans l'editlog.
Or l'enum n'a plus la traduction.

=> je propose, si l'enum n'existe pas mettre la valeur brute et non 'ref. not found'.

Un exemple : historique de Guillaume Plique

**Comment by paulgirard** [comment]
J'ai trouvé un bug dans le système de création de labels à partir des clefs d'organisation.
J'isole le problème dans cette issue : https://github.com/SciencesPo/isari/issues/491

Espérons que ça suffise. j'en reste là pour cette issue.
