### ISSUE TITLE
Régression dans les data : Champ Organisation vide dans les données existantes

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#485]
Sur la release déployée le 19 oct en PRPD, sur les activités existantes , le champ Organisation dans le bloc "Organisations impliquées" dans les Activités est vide :
![image](https://user-images.githubusercontent.com/22589536/32041561-c38d02d4-ba34-11e7-93b3-bba62b45d11e.png)

Cela se produit sur n'importe quelle activité. A noter que quand on crée une nouvelle activité, et qu'on remplit ce champ, il apparaît bien.

Cela se produit également sur les Membres, mais de manière aléatoire (?) : 
Exemple : sur la fiche de Charlotte Halpern, les 7 Unités de recherche auxquelles elle est rattachée sont vides. La tutelle dans le Parcours est vide, l'Organisation dans les 2 diplômes aussi (voir copie d'écran ci-après).
Sur la fiche de Jenny Andersson, les orga sont remplies !
J'ai testé avec 2 rôles différents (admin central et admin centre CEE,) et le comportement est le même.

![image](https://user-images.githubusercontent.com/22589536/32063578-d51ec508-ba77-11e7-92c7-f4335f750add.png)

**Comment by paulgirard** [comment]
C'est lié à #292.
Concrètement le rassemblement des FK ne se fait pas par modèle.
On observe que l'appel à organisations/id1,id2,id3,/string?... contient des id de people.
Du coup l'api répond 404 et plus aucune FK d'orga ne sont résolues
