### ISSUE TITLE
Impossible d'ajouter une Distinction dans une fiche Membre

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#487]
Sur la release livrée en PPRD le 6 nov, essayer d'ajouter un Diplôme et Distinction de type **Distinction** dans une fiche Membre , on reçoit une erreur systématique. Aucune info n'est sauvegardée.

De plus, le système oblige à renseigner un type de diplôme alors que cela n'est pas demandé (cf en PROD), or on doit pouvoir renseigner un diplôme, double-diplôme ou une cotutelle sans obligatoirement renseigner le type de diplôme.

![image](https://user-images.githubusercontent.com/22589536/32490315-01e14342-c3b3-11e7-9747-1a20fd505d79.png)

ça se produit quel que soit le rôle

**Comment by paulgirard** [comment]
en faite même problème que #488
