### ISSUE TITLE
 A la fermeture d’une fiche, prévoir une fenêtre qui demande si on veut ou non sauvegarder.

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#508]
pour chaque formulaire de l'appli 
si il y a eu une modif mais pas de save et que l'utilisateur ferme la fenêtre ou clique un lien pour ouvrir une nouvelle page dans la même fenêtre alors on affiche un modal comme celui de vérification d'existence avant création qui demande à l'utilisateur si il veut sauvegarder ou abandonner les modifications.

**Comment by LGAGELIN** [comment]
Libellés Français et  Anglais des messages du modal :
« Souhaitez-vous sauvegarder les modifications ? » OK / Annuler
« Would you like to save changes ? » OK / Annuler

**Comment by paulgirard** [comment]
Attention on ne pourra pas gérer tous les cas : 
- changement de menu dans l'application : ok
- fermeture d'onglet : pas garantie car ce genre d'événement sont utilisés par les système des pub et potentiellement bloquer par le navigateur.

**Comment by t8g** [comment]
![image](https://user-images.githubusercontent.com/639759/40773837-5365915c-64c4-11e8-877b-87325e39e889.png)


Normalement ceci s'affiche si on ferme ou change l'url un onglet.

**Comment by t8g** [comment]
Et un message + sympa si navigation interne

![image](https://user-images.githubusercontent.com/639759/40773905-86075d0c-64c4-11e8-90ba-1cc1e4f546fa.png)

**Comment by LGAGELIN** [comment]
Ouvrir une fiche, la pastille est grise, modifier les Nationalités, la pastille devient rouge avec le nb de nationalités que j'ai modifiées (il compte tout : chaque suppression, chaque ajout)
Sauver, la pastille devient grise
Cliquer sur le menu Organisations => le message apparaît alors qu'il ne devrait pas. 
Cliquer sur Rester, puis cliquer  nouveau sur un menu (tableau Activités par exemple), le message apparait systématiquement et la pastille est toujours grise. Voir copie d'écran ci-après

![image](https://user-images.githubusercontent.com/22589536/40777311-d23bc6dc-64cd-11e8-83e2-b443225ec103.png)

**Comment by LGAGELIN** [comment]
Même comportement à la sélection d'une fiche dans le tableau dans lequel on se trouve. Si on fait une modif dans une fiche, et qu'on change de fiche, le message apparaît, très bien. Cliquer sur Rester, cliquer sur la pastille rouge pour sauver, elle devient grise, très bien, mais au clic sur une autre fiche du tableau, le message réapparaît.

**Comment by t8g** [comment]
Ah oui effectivement ...
Je corrige ça

**Comment by LGAGELIN** [comment]
ça marche très bien, sauf dans le cas du changement de langue. Si on change de langue de l'interface de l'appli, le système n'affiche pas le message, et les modifications sont perdues, la pastille qui était rouge passe au gris.

**Comment by LGAGELIN** [comment]
ça ne fonctionne pas non plus dans le cas d'une nouvelle fiche.
Ajouter une nouvelle personne/activité/orgabisation, Remplir 2 champs, la pastille rouge s'affiche, puis  cliquer sur un menu pour accéder à un tableau par exemple,  le message n'apparaît pas, la fenêtre se ferme, les modifs sont perdues.

**Comment by LGAGELIN** [comment]
En fait, non il ne ferme pas l'ancienne fiche dans le cas d'une nouvelle fiche, celle-ci est ouverte dans une ouvert onglet. Donc pas de soucy
