### ISSUE TITLE
modification de schéma /enum

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#509]
**Sur Activity :** 

Ajouter un nouveau "type d'activité"  pour renseigner les colloques, séminaires, conférences, workshops organisés par le labo  : "manifestation scientifique" / "scientific event"

Dans la catégorie "Programme de financement" rajouter "Plan d'action ANR"

Compléter les listes d'enums « instrument de financement » et  « programmes de financement »

**Sur People**
Dans le bloc coordonnées, prévoir une ligne « page web »

Dans grade, pour les professeurs d’université, les catégories sont de « première classe » et de « deuxième classe »

Dans statut 'chercheur' ajouter un grade 'inscrit.e en HDR' en anglais 'professoral thesis'

Dans Parcours, champ "type de contrat" : ajouter "contrat de vacation"

Pour répondre au besoin de déclaration du parcours à et hors Sciences Po  cf https://github.com/SciencesPo/isari/issues/514

**Comment by LGAGELIN** [comment]
Pour le nouveau grade **Inscrit.e en HDR**, vérifier que dans l'export des Effectifs, ils doivent sortir dans l’onglet Faculté Temporaire, comme les Doctorants.

**Comment by paulgirard** [comment]
je fais une issue avec ce dernier commentaire
