### ISSUE TITLE
alertes si édition sur champs accessMonitoring

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#513]
#Certains champs ont été signalé comme sensible grâce au champs accessMonitoring (prévu pour editLog).

Dans l'interface, tout champs ayant été marqués comme accessMonitoring sont concerné par un nouveau système d'alerte. Dans une configuration on indique la liste des valeurs accessMonitoring sur lesquelles on souhaite déclencher une alerte.
 
Si un utilisateur édite un champs qui a un tag accessMonitoring (pointé par la conf d'alerte), alors le client a ce comportement : 
Si le champs protégé contient une valeur et n'est pas une liste et l'utilisateur n'est pas central_admin : 
- [ ] il est disabled par défaut
- [ ] il a une icône cadenas fermé https://material.io/tools/icons/?icon=lock&style=baseline

Si le champs protégé est vide ou et n'est pas une liste  ou si l'utlisateur est central_admin: 
- [ ] il est enabled par défaut
- [ ] il a une icône cadenac ouvert https://material.io/tools/icons/?icon=lock_open&style=baseline

Si l'utilisateur click sur l'icône cadenas fermé : 
- [ ] un message de type warning rouge (comme error de save) apparaît avec le message suivant : 
« Vous êtes sur le point de modifier un champ prioritaire.»
« You’re about to modify a priority field.» 
- [ ] le champs est enabled et accepte les modifications

Si le champs protégé est une liste non vide et l'utilisateur n'est pas central_admin : 
- [ ] le bouton ajouter doit être inactif
- [ ] le bouton suppression des objets ne doit pas apparaître ou être disabled
- [ ] les champs des objets de la lsite sont tous disabled
- [ ] un cadenas fermé est ajouté  à côté des icônes ajouter et supprimer

Si le champs protégé est une liste vide ou si l'utlisateur est central_admin: 
- [ ] un cadenas ouvert est ajouté à côté des icônes ajouter et supprimer

Pour le moment on laisse le cadenas ouvert jusqu'au prochain rechargement.

- [x] ajouter une configuration qui liste les valeurs de accessMonitoring qui déclenche des alertes
- [x] il faut que le serveur envoie les infos d'accessMonitoring au client

- [ ] ajouter ces tags accessMonitoring : 
- Rattachement labo (tout le bloc) : déjà inclus dans le tag DS
- Rattachement département (tout le bloc) : idem 
- Statut et grades (tout le bloc) : idem
- 3 champs du bloc Données contractuelle : Tutelle, Date début, Date de fin. Ces champs tagés à l'heure actuelle DRH passeront donc en tag DS (confirmé avec Elsa)

**Comment by LGAGELIN** [comment]
Tag à monitorer = DS
Il faudra basculer les champs du bloc "Données contractuelles" qui portent à l'heure actuelle le tag DRH vers le tag DS.

**Comment by LGAGELIN** [comment]
Libellés français et anglais du message d'alerte :

« Vous êtes sur le point de modifier un champ prioritaire. Souhaitez-vous poursuivre ? » oui/non

« You’re about to modify a priority field. Would you like to continue ? » yes/no

**Comment by paulgirard** [comment]
Ces messages ne sont pas cohérent avec le comportement défini.
Les messages ne sont que des avertissements et ne pose pas de question.
Je contre propose donc :
« Vous venez d'éditer un champ prioritaire. Merci de bien vérifier cette modification avant de sauvegarder »

« You’ve just edited a priority field. Please check twice before saving. »

**Comment by LGAGELIN** [comment]
les cadenas apparaissent au bon endroit :)

**Comment by LGAGELIN** [comment]
Est-il possible de modifier le titre et le contenu du message qui apparaît ?

![image](https://user-images.githubusercontent.com/22589536/40781352-d318783a-64db-11e8-83ba-8702cdb9c0dd.png)

Dans le Titre, enlever le "s" à la fin de CHamp =>  Champ prioritaire   
Pour le message , ajouter "saisir ou " => Vous êtes sur le point de saisir ou modifier un champ prioritaire
