### ISSUE TITLE
Problème layout Barre de menu de bas de page

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#516]
Nouveau document  dans le bouton Aide : Glossaire

**Comment by LGAGELIN** [comment]
URL : http://www.sciencespo.fr/scpolib/ISARI/ISARI_Glossaire.pdf

**Comment by LGAGELIN** [comment]
Le document a été ajouté sur l'URL indiquée. A vérifier

**Comment by LGAGELIN** [comment]
Plusieurs retours de tests : 

- Sur l'écran d'accueil des labos et par labo, la barre de bas de page n'est plus visible, et non plus par scroll de la fenêtre. Pour la voir, il faut réduire la taille de l'écran à 75 % au moins, ce qui fait beaucoup.
On la voit encore moins sur les tableaux, quand on ouvre une fiche. Elle n'est pas visible du tout, il faut réduire l'écran au moins à 33% pour l'apercevoir... et encore si on n'a pas ouvert de blocs dans le formulaire 

- Le menu Aide est devenu un bouton. Est-il possible qu'il ne soit pas un bouton comme les autres éléments de la barre, et comme c'était le cas avant ?

**Comment by paulgirard** [comment]
Ok je rouvre
