### ISSUE TITLE
Perte d'informations sur le calendrier

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#523]
On a perdu des informations sur le calendrier des champs Date  :

"mois" et "année" ont disparu dans le haut du calendrier.

![image](https://user-images.githubusercontent.com/22589536/40535813-772ebfd2-600a-11e8-8e6c-ef94fb8d20de.png)

Applicable sur tous les champs Dates des formulaires ainsi que dans les filtres Dates des tableaux.

**Comment by LGAGELIN** [comment]
C'est mieux, sauf pour les Jours, il n'y en a que 8 jours 

![image](https://user-images.githubusercontent.com/22589536/40624552-a1b06314-62ad-11e8-833c-4a8daaf8cc16.png)

**Comment by t8g** [comment]
Bizarre, je n'ai pas ce comportement.
![image](https://user-images.githubusercontent.com/639759/40626731-b4799ecc-62ba-11e8-8932-e462d009c849.png)

Peut-être des conditions particulières. Pouvez-vous m'aiguiller ?

**Comment by t8g** [comment]
Ok ! Vu sur les jours ! Je corrige ;)

**Comment by t8g** [comment]
Pb d'interaction avec le header. Corrigé.

**Comment by LGAGELIN** [comment]
c'est mieux :)
