### ISSUE TITLE
icônes I apparaissent à tort sur les champs

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#524]
Vérifier l'affichage des icônes I, dont certains s'affichent à tort.

Exemples :

Dans Accès ISARI : l'icône I est affiché pour le champ "Centre de recherche" et indique qu'on peut ajouter plusieurs valeurs, alors qu'on ne peut mettre qu'une seule valeur
![image](https://user-images.githubusercontent.com/22589536/40546258-1802a814-602f-11e8-8837-203ac5d77da8.png)

Dans Tutelle : il y a 2 icône I,  l'une indique qu'on peut renseigner plusieurs valeurs, ce qui est faux, l'autre indique bien l'info du champ Tutelle. 

![image](https://user-images.githubusercontent.com/22589536/40536313-fffe1a32-600b-11e8-9985-d626a666653b.png)

**Comment by t8g** [comment]
Corrigé

**Comment by LGAGELIN** [comment]
ça semble OK
