### ISSUE TITLE
Liens vers Foreign Key ne sont plus affichés sur l'interface

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#525]
Les liens cliquables ne sont plus visibles sur l'interface : que ce soit des liens vers des Organisations ou des Personnes 

![image](https://user-images.githubusercontent.com/22589536/40537422-29393a5a-600f-11e8-8290-389d08c9706e.png)

**Comment by LGAGELIN** [comment]
Liens depuis les Activités : OK

Liens depuis les Membres 
- UR : OK
-  Parcours (Tutelle) : OK
- Diplômes et Distinctions : KO
- Activités Responsabilités : KO
 Exemple fiche de Ruben DURANTE. On ne voit pas les liens dans  ni dans

**Comment by t8g** [comment]
Pour les champs multiples, les "chips" (c'est le nom du composant) sont des liens.

Ceci est un lien.

![image](https://user-images.githubusercontent.com/639759/40648304-69a8ed20-632e-11e8-9a14-d575c93057a4.png)

**Comment by t8g** [comment]
Je peux peut-être essayer d'ajouter un trait sous le nom, pour le faire plus ressembler à un lien traditionnel

**Comment by t8g** [comment]
![image](https://user-images.githubusercontent.com/639759/40648526-f7301416-632e-11e8-9362-c09f5014d752.png)


Est-ce mieux ?
