### ISSUE TITLE
Problème affichage listes déroulantes à enums nestées

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#527]
Les listes déroulantes à enums nestés ne s'affichent plus quand on clique sur le champ vierge. Il faut saisir une ou plusieurs lettres pour que la liste apparaisse.
En revanche, une fois que la valeur est saisie, la liste apparaît.

Fiche Membre :

- dans le bloc "statuts et grades " : pour "Statut" la liste s'affiche, mais pas pour "Grade"

-  bloc "diplômes et distinctions : pour "Type de distinction", la liste s'affiche, mais pas pour "Type de diplôme"

- bloc "activités et responsabilités" : la liste s'affiche pour "Type d'activité", mais pas pas pour "Plus précisément" et "Rôles"

Il semble donc que ce soit les listes nestées qui soient impactées. 

Fiche Activity :
bloc Financement : le menu déroulant apparaît pour "Type" mais pas pour "Instrument de financement"

**Comment by t8g** [comment]
À priori corrigé

**Comment by LGAGELIN** [comment]
Impossible de sélectionner une entrée dans la liste, que ce soit à la souris ou en saisissant des lettres, rien ne s'affiche dans le champ

A part ça, les listes s'affichent bien, mais vérifier que ce sont les bonnes. Exemple pour Grade dans Statut, il manque Inscrit en HDR pour Enseignant Chercheur, Chercheur Enseignant, et Chercheur, et on les avait dans la version précédente pour tous ces statuts sauf Chercheur.

**Comment by t8g** [comment]
Je pense que l'ensemble des soucis est corrigé.

Je ne vois pas de quelle liste vous parlez sur "Dans People, dans le champ Méthodes du bloc Thémtiques," est-ce sur une fiche membre ?

Pour le Enseignant Chercheur, Chercheur Enseignat et Chercheur, les données affichées correspondent bien aux énums https://github.com/SciencesPo/isari/blob/master/specs/enums.nested.json#L1145

**Comment by LGAGELIN** [comment]
Il y a une copie d'écran dans mon commentaire. C'est dans Activity, bloc Financement, champ Instrument de financement

**Comment by LGAGELIN** [comment]
Autre endroit où un item Object Object apparaît, dans fiche Membre, bloc "Activité et responsabilités", dans le cas suivant : Dans type d'activité, choisir "activités éditoriales", saisir n'importe quoi et valider cette valeur dans "Plus précisément", recliquer sur la liste =>
![image](https://user-images.githubusercontent.com/22589536/40710036-e4b7f8ac-63f7-11e8-8b63-bcd2a0481428.png)

Puis, si on modifie Type d'activité, et qu'on reclique aussitôt sur Plus précisément, Object Object apparait dans la liste

**Comment by t8g** [comment]
Pas réussi à reproduire

**Comment by LGAGELIN** [comment]
Pour info, on l'a aussi sur Rôle dans le même bloc

**Comment by t8g** [comment]
Corrigé (non sans mal)
