### ISSUE TITLE
En-tête des tableaux : améliorer l'affichage de "Choix des colonnes" 

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#529]
1. Est-il possible d'avoir un bouton "Choix des colonnes" (comme avant) plutôt qu'un libellé ? Cela permettrait d'éviter que quand aucune colonne n'est sélectionnée, on ne voit pas tout le libellé :
![image](https://user-images.githubusercontent.com/22589536/40547552-8cf18c32-6032-11e8-8002-a39c0aca2dae.png)

2. Est-il possible de réduire la taille de la police d'affichage de la liste des colonnes , elle devrait être identique à celles des lignes du tableau

![image](https://user-images.githubusercontent.com/22589536/40547356-f8935dc2-6031-11e8-8b69-887f782704c6.png)

3. Il n'est pas pratique de ne pas tout voir en une seule fois pour cocher plusieurs items (c'était mieux avant)

**Comment by t8g** [comment]
Des changements.
Par contre le passage au format bouton est assez complexe (on utilise maintenant un composant identique à un champ).

Voir si cela convient
