### ISSUE TITLE
Problèmes sur les listes multivaluées 

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#530]
La liste ne s'affiche pas toujours. Exemple dans le champ Méthodes. On arrive dans la fiche, on clique sur Méthodes, rien ne s'affiche, on reclique, ça s'affiche

Il est possible d'ajouter plusieurs fois la même valeur, ce qui n'était pas le cas avant, il faut revenir à la situation antérieure. Notamment dans tout le Bloc Thématiques et domaines de recherche : Domaines ERC, Méthodes, Discipline, etc....

**Comment by t8g** [comment]
Les 2 soucis remontés ici sont corrigés.
