### ISSUE TITLE
Problèmes sur EditLogs

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#536]
Lorsqu'on arrive dans ISARI, et qu'on demande à accéder au  labo médialab  sur les Membres, puis qu'on demande directement l'accès au Tableau EditLogs Membres:  le tableau demandé  s'affiche pas.

Demander ensuite l'accès à n'importe quel autre tableau Editlog : même comportement, le tableau ne s'affiche pas.
Même comportement pour le CERI. En revanche, ça fonctionne correctement pour le CEE.

Ensuite, si on clique sur le tableau Organisations, puis qu'on demande directement l'accès aux EditLogs, les tableaux EditLogs s'affiichent bien sauf celui des Membres qui mouline dans le vide.

Il semble donc qu'il y ait 2  problèmes : 
- les Tableaux EditLogs ne s'affichent pas suivant le contexte de navigation et le labo
- Pour tous les labos, les tableaux EditLogs Membres moulinent systématiquement dans le vide.

**Comment by t8g** [comment]
Il manquait le champ DSPRIO dans les enums

```json
    "accessMonitoring": [
        {
            "value": "DRH",
            "label": {
                "fr": "DRH",
                "en": "HR"
            }
        },
        {
            "value": "DS",
            "label": {
                "fr": "DS",
                "en": "scientific direction"
            }
        },
        {
            "value": "DSI",
            "label": {
                "fr": "DSI",
                "en": "IT services"
            }
        },
        {
            "value": "DSPRIO",
            "label": {
                "fr": "DS Prio",
                "en": "DS Prio"
            }
        }
    ]
```

**Comment by LGAGELIN** [comment]
ça marche nickel 👍
