### ISSUE TITLE
Enums à ajouter pour l'activity de type Manifestation Scientifique

### ISSUE THREAD

**Issue by LGAGELIN** [SciencesPo/isari#546]
Ajouter les enums suivants pour l'activity Manifestation scientifique =(activityTypes=" event") dans le fichier enums.nested.json 

Dans "activityOrganizationRoles", ajouter :
Partenaire
Coordinateur
Participant
Organisateur

 Pour "activityPeopleRoles" , ajouter :
Intervenant
Modérateur
Keynote lecturer
Responsable scientifique
Discutant
Président (séance, session, atelier…)
Organisateur

**Comment by LGAGELIN** [comment]
Ajouter les traductions des libellés en anglais qui viennent d'être fournies :

Menu « Activités », sous-menu « manifestation scientifique »

1.	activityOrganizationRoles
Partenaire = Partner
Coordinateur = Coordinator
Participant = Participant
Organisateur = Convener

2.	activityPeopleRoles

Intervenant = Speaker
Modérateur = Moderator
Keynote lecturer = Keynote lecturer
Responsable scientifique = Scientific coordinator
Discutant = Discussant
Président (séance, session, atelier…) = Chairman
Organisateur = Convener

**Comment by MistretzulPrietenos** [comment]
Déployé en PROD  @LGAGELIN  @jri-sp
