### ISSUE TITLE
export tableau

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#55]
ajouter un bouton qq part dans le footer du tableau pour télécharger le tableau courant totue page confondue aux formats par ordre de préférence XLSX, CSV, ODS.

La génération du tableau peut être faite côté serveur ou client ?

Cette fonctionnalité n'est accessible que aux user de rôle admin qqchose (research_admin, central_admin, research_editor, central_reader)

**Comment by Yomguithereal** [comment]
C'est fait pour le CSV et le XLSX. Pas géré le rôle encore.
