### ISSUE TITLE
éditer les dates en mode texte genre avec une regex en live ?

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#58]
édition de date en :
2017
2017-12
2017-12-01
avec un contrôle par regex

**Comment by t8g** [comment]
Trouvé https://github.com/text-mask/text-mask
Mais complexe à faire marcher : l'input change de statut. 
Soit il affiche la date formatée (14 février 2018)
Soit iso (2018-02-14)
Mais dans le 1er cas le masque s'applique tout de même ce que l'on ne veut pas.
Il faudrait que je trouve un moyen que le masque ne s'applique que quand je le décide.

**Comment by paulgirard** [comment]
Sinon plus simplement on paramètre le composant pour le rendre éditable en texte ou pas.
Si il est éditable en texte alors il affiche toujours la date en iso.
Si pas éditable, on ne modifie que par le module interactif et on affiche la jolie date ? 

Comme ça on n'a pas le problème compliqué et on garde la possibilité de réserver l'édition texte à des cas particulier ?

**Comment by t8g** [comment]
Presque bon
Juste un pb de validation (genre comme si le 35 janvier n'existait pas)
