### ISSUE TITLE
générer le schema mongoose à partir du meta

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#6]

**Comment by naholyr** [comment]
La logique de traduction d'un champ du `schema.meta.json` en champ compréhensible par `Mongoose` est implémentée ici : https://github.com/SciencesPo/isari/blob/3824378d0614b425cd75b173d177765a14dab218/server/lib/schemas.js#L50-L150

Une description plus "humaine" de ces traductions se trouve directement dans le fichier `schema.meta.json` pour référence : https://github.com/SciencesPo/isari/blob/3824378d0614b425cd75b173d177765a14dab218/specs/schema.meta.json#L4-L31

Au démarrage de l'application, `app.js` charge le modèle et affiche une erreur en rouge si le schéma n'a pu être converti.

**Reste à faire** : traitement de l'enum par sous-clé

**Comment by naholyr** [comment]
Note : on utilise [debug](https://www.npmjs.com/package/debug) pour les messages de debugging côté serveur. Dans le cas de ce module, la clé de debug est **`isari:schema`**

![selection_373](https://cloud.githubusercontent.com/assets/214067/19068837/83ffd7a4-8a24-11e6-97d6-e1a36d3c2347.png)

**Comment by naholyr** [comment]
Mise en place des enums dépendants, testée OK (à passer en test unitaire) :

```js
const u = new model.People({
	name: 'Bob',
	personalActivities: [
		{
			personalActivityType: 'something',
			personalActivitySubtype: 'something else'
		}
	]
})

u.save().catch(console.error)
```

Erreur :

```js
{
  message: 'People validation failed',
  name: 'ValidationError',
  errors: 
   { 'personalActivities.0.personalActivitySubtype': 
      { message: 'personalActivitySubtype does not allow "something else" as of enum "personalActivityTypes.$personalActivityType"' },
     'personalActivities.0.personalActivityType': 
      { message: '`something` is not a valid enum value for path `personalActivityType`.' } } }
```

On corrige `personalActivityType` = `encadrement`. Erreur :

```js
{
  message: 'People validation failed',
  name: 'ValidationError',
  errors: 
   { 'personalActivities.0.personalActivitySubtype': 
      { message: 'personalActivitySubtype does not allow "something else" as of enum "personalActivityTypes.$personalActivityType"' } } }
```

On corrige `personalActivitySubType` = `mémoire` : OK :)

**Note** : j'ai cherché comment générer un message d'erreur plus explicite (notamment injecter dedans la valeur de `personalActivityType`) mais l'API "validator" ne le permet pas. Si besoin, on pourrait modifier ça en passant par un hook *pre-save*.
