### ISSUE TITLE
npm watch:server est éternel

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#60]
On n'arrive pas à quitter le watch:server proprement ?
En plus il fait des choses indescriptibles au terminal de @Yomguithereal

**Comment by naholyr** [comment]
Comme je n'arrive pas à reproduire j'imagine que ça doit être lié au terminal Mac, j'aimerais plus d'infos :

* Quel logiciel de terminal fenêtré ?
* Quel shell ?
* Est-ce reproductible dans d'autres environnements (s'il y a par exemple moyen d'y accéder autrement que via iTerm) ?
* Au lieu de `npm run watch:server` que donnent les commandes suivantes, lancées depuis le dossier "server" ?
  * ``npm run watch:server -- -I``
  * ``./node_modules/.bin/nodemon -e js,json,toml -w . -w ../specs server.js``
  * ``./node_modules/.bin/cross-env NODE_ENV=development ./node_modules/.bin/nodemon -e js,json,toml -w . -w ../specs server.js``
  * ``NODE_ENV=development ./node_modules/.bin/nodemon -e js,json,toml -w . -w ../specs server.js``

**Comment by naholyr** [comment]
ping @Yomguithereal @paulgirard pour tester les commandes
