### ISSUE TITLE
delete objects ?

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#63]
## Enjeux 1 : est ce que ce qu'on veut supprimer ce qui est lié ? 
- détecter ce qui est lié
- prévenir le user ?

## Enjeux 2 : qui a le droit ?
Fonctionnalité dispo que pour les admins centraux si l'objet est lié.
Aux utilisateurs ayant droit d'écriture autrement ? 

## enjeux 3 : garder une trace de l'objet
Soit on flag ce qui demande de filtrer toutes les requêtes
Soit on fait confiance à l'edit log

## Décision 
- les suppressions ne sont accessibles qu'au rôle central_admin et center_admin et center_editor
- action de suppression : 
       - vérifier si une foreign key pointe sur l'objet à supprimer
       - si oui, refuser de supprimer et afficher un message listant les liens de l'objet en précisant que la suppression n'est possible que si il n'y a plus de liens
       - si non, demander confirmation de suppression puis supprimer pour de vrai

## nouvelle proposition

- [ ] ajouter à chaque fin de formulaire une box repliée par liste non vides renvoyées par l'api "relations" intitulées : "activités liées", "organisations liées", "personnes liées".
- [ ] chaque boite contient une liste des objets renvoyées par l'API relations : label et icône "open_in_new" permettant d'ouvrir la page de l'objets liées dans un nouvel onglet
- [ ] en bas à droite du formulaire en dessous des boites d'objets liés on ajoute un bouton supprimer du même style que "ajouter". Si il est actif le bouton déclenche la modale "êtes vous sûr" puis appelle l'api de suppression.
- [ ] ce bouton est disabled si il y a des objets liés (renvoyé par relations) 
- [ ] un texte à gauche de ce bouton "impossible de supprimer car cette personne|organisation|activité est liée" qui n'est visible que si il y a des objets liés

**Comment by paulgirard** [comment]
Je demande un avis à @Yomguithereal

**Comment by t8g** [comment]
Fait.
Reste la redirection après suppression (en attente d'une correction api)

**Comment by Yomguithereal** [comment]
Je bouge dans à tester.

**Comment by t8g** [comment]
En fait c'est bon et la redirection est faire

**Comment by LGAGELIN** [comment]
Je rouvre car en tant que Membre, je peux supprimer.

**Comment by paulgirard** [comment]
Comportement normal.

**Comment by LGAGELIN** [comment]
Alors tous les rôles peuvent supprimer dès qu'il n'y a pas de lien entrant ?

**Comment by paulgirard** [comment]
éditable = supprimable
