### ISSUE TITLE
flèches de multipage tableau 

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#65]
Les flèches actuelles renvoient à la première ou à la dernière page.
On s'attend à ce que ça fasse next page.

=> changer leur icône en double flèche pour signifier ce comportement

=> ajouter des boutons next/previous page avec l'icône actuelle

=> enlever les boutons ...

**Comment by t8g** [comment]
Pour les "...", il faut bien matérialiser le fait qu'il existe des pages avant (et surtout) après.
Je peux virer l'action dessus, mais avoir l'info me semble nécessaire.

**Comment by t8g** [comment]
@paulgirard dis moi si le résultat te convient

**Comment by paulgirard** [comment]
parfait !
