### ISSUE TITLE
tableau largeur colonne fixe et éditable à la main

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#68]
est il possible de laisser l'utilisateur fixé la largeur des colonnes ?

**Comment by t8g** [comment]
À voir si le fonctionnement va

**Comment by t8g** [comment]
@paulgirard tu me diras si il faut faire autrement / ajuster

**Comment by paulgirard** [comment]
En l'état ça me semble bien.
Pour aller plus loin il faudrait laisser le user modifier la taille et ça on verra plus tard.
Je clos.
