### ISSUE TITLE
dumper la mongo dans des json à plat par objet dans un git

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#72]
un dossier par collection
un fichier json par document mongo
un commit par appel du script.

script qui serait appelé par un cron genre.

**Comment by Yomguithereal** [comment]
Donc je peux drafter ça dans mon dossier `script`? Pas besoin d'avoir un appel à l'API pour ça non?

**Comment by Yomguithereal** [comment]
@paulgirard, le script est fini et se trouve dans la branche `dump-script`. Je merge dès que ça te va. Il ne fait pas les actions git automatiquement par contre. Il se contente de dumper en JSON les items. On verra le reste après.
