### ISSUE TITLE
étude de performance serveur

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#74]

**Comment by naholyr** [comment]
* Performance de `/model?applyTemplates=1` → bons résultats en modifiant la méthode de *populate*
* Note: au passage j'ai ajouté de la mémoization à un endroit qui me semblait pertinent, ça ne l'était finalement pas néanmoins je pense que la mise en cache des résultats des fonctions asynchrones reste intéressant

**Comment by naholyr** [comment]
On s'arrête là pour le moment a priori "populateAll" était le seul gouffre à perf
