### ISSUE TITLE
Mettre un serveur de préprod

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#76]
caractéristiques serveur : 
- mongo 3.2.9
- Elasticsearch 2.3.5
- mongo-connector
- kibana 4.5 (pas indispensable si vous souhaitez alléger on peut le virer)
- node.js 6.7 qui fournit une API REST
- git (voir ci-dessous)
- un serveur web de votre choix qui distribue l'appli angular 2
- il faut que le serveur puisse servir du HTTPS car les données sont sensibles

# Docker

Il y a déjà un docker dev pour la partie mongo/mongo-connector/ES/kibana :
https://github.com/SciencesPo/isari/tree/master/server/dev_docker

Pour le build du code client : 
https://github.com/SciencesPo/isari/tree/dev/client#build

Pour le build/start du code serveur :
https://github.com/SciencesPo/isari/tree/dev/server#production

Pour initier la base de données, récupérer les données initiales et lancer l'import : https://github.com/SciencesPo/isari/tree/master/scripts#importing-the-initial-data

Cet import ne sera fait qu'une fois.

# Backup

Il faudrait faire un backup de la mongo comme d'habitude.
On prévoit en plus de ce backup de réaliser un versioning de la mongo dans un git local. Ce serait sans doute une bonne idée de répliquer ce git dans un gitlab.
L'argument pour le versioning est d'utiliser git pour avoir de l'incrémental au niveau objet.

**Comment by paulgirard** [comment]
demande envoyée.

**Comment by Yomguithereal** [comment]
Est-ce qu'on peut fermer ça désormais?
