### ISSUE TITLE
ajouter un lien/icône  edit à côté de chaque valeur de type FK dans les formulaires 

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#78]
Ce bouton edit ouvre un onglet et propose le formulaire pleine page sur l'objet pointé.
Idéalement ce bouton ne devrait etre présent que si l'utilisateur a accès aux détails de cet objet.

ça sous-entends que le peuplement des objets de type FK doit embarqué une notion de droit pour l'utilisateur connecté. @naholyr attention à ça pour ton taff sur les rôles et sur la potentielle refonte des toString.

**Comment by t8g** [comment]
Sur les champs multiples, tu vois ça comment @paulgirard  ?

**Comment by naholyr** [comment]
Noté pour les permissions, il faudra en effet que je check les permissions sur l'objet ciblé par la FK et que je les propage au champ lui-même pour le front

**Comment by paulgirard** [comment]
Pour mémoire on a évoqué l'idée d'ajouter une icône "lien" à côté de l'icône "croix" dans le cas des champs multiples.

**Comment by t8g** [comment]
Fait sur les select
Reste à faire sur multi select

**Comment by t8g** [comment]
Done
