### ISSUE TITLE
intégrer le footer

### ISSUE THREAD

**Issue by Yomguithereal** [SciencesPo/isari#79]
Intégrer les informations du footer. En attente des éléments métiers.

Voici les infos à insérer sur la barre en footer des pages ISARI :

- Remplacer @2015 SciencesPo, par @2016 SciencesPo

- Lien pour Mentions Légales et CGU : ​http://www.sciencespo.fr/scpolib/​ISARI/​ISARI_MentionsLegales​.pdf

​- ​L​ien pour Gérer vos accès : ​http://www.sciencespo.fr/ressources-numeriques/content/gerez-vos-acces

​- ​​​Pour toute question​, isari@sciencespo.fr

**Comment by LGAGELIN** [comment]
Les liens doivent s'ouvrir dans une nouvelle fenêtre du navigateur.

**Comment by Yomguithereal** [comment]
@AdrienCossonSciencesPo je te laisse ajouter les `target=_blank`

**Comment by AdrienCossonSciencesPo** [comment]
Done N Pushed
