### ISSUE TITLE
largeur des champs du formulaire

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#82]
les champs du formulaire sont bloqués à une taille fixe plutôt petite.
@t8g  as tu eu des infos sur ce problème ?

**Comment by t8g** [comment]
Non pas re-fouillé. Je veux bien un coup de main de @Yomguithereal là-dessus

**Comment by Yomguithereal** [comment]
Je check un coup. Mais je vous préviens, je ne suis pas le roi du CSS.

**Comment by t8g** [comment]
Si besoin j'irais m'incruster à l'Atelier Iceberg pour demander à Sam, leur inté.

**Comment by Yomguithereal** [comment]
Concept permettant d'avoir le form en fullwidth [ici](https://github.com/SciencesPo/isari/commit/85d52147719f6aed3cf898850b49c6a21e5c36e4) @t8g. Ca te semble correct?

**Comment by t8g** [comment]
J'ai mis ça sur dev
Vous me direz

**Comment by paulgirard** [comment]
bon du coup c'est l'autre extreme.. 
J'essaie de jouer avec el CSS mais au pire on garde ça pour le moment.
Il faudra trouver une solution à terme

**Comment by paulgirard** [comment]
Une piste d'amélioration consisterait à appliquer un min-width et un max-width au TD contenant les input.

**Comment by t8g** [comment]
Et virer les td pour passer les conteneurs de chaque champs en display:
"table-cell" ?

Le jeu. 24 nov. 2016 à 10:21, Paul Girard <notifications@github.com> a
écrit :

**Comment by paulgirard** [comment]
Pour se sortir de ce problème on pourrait fixer une taille par type de champs ?
voir l'issue #167

**Comment by t8g** [comment]
Qqs corrections : à voir si ça vous convient
