### ISSUE TITLE
boutons - et + dans les champs multiples

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#90]
Il faudrait améliorer l'ergonomie car en l'état les utilisateurs ne comprennent par le multiple.

L'idéal serait de n'indiquer le nom du champs qu'une fois en haut du bloc des lignes multiples.
Ajouter à ce label de bloc multiples une icône plus.
A chaque bloc unitaire des multiples, on ajoute en début de ligne une icône moins mais sans libellé.

**Comment by t8g** [comment]
oui ?

**Comment by paulgirard** [comment]
On s'en occupera plus tard.
On fera une passe sur le look and feel à un moment.

Néanmoins je précise l'idée dans la description

**Comment by paulgirard** [comment]
il y a un bouton - par ligne de layout alors qu'il n'en faut qu'un seul par sous-objet
