### ISSUE TITLE
import des doctorants

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#91]
- [x] diplômes antérieurs des doctorants
- [x] ajouter le gradeAcademic aux doctorants avec startDate/endDate du doctorat

créer une activité doctorat et hdr
- [x] créer une activité de type doctorat
- [x] ajouter Sciences Po avec le rôle inscription
- [x] attacher le labo à l'activité de doctorat avec le rôle inscription
- [x] attacher le actityPeopleRole "doctorant"
- [x] attacher les membres de jury
- [ ] ajouter un financement en fonction de la colonne LIB_SOURCE_FINANCEMENT

**Comment by Yomguithereal** [comment]
Presque fini. Certains détails ont changé.

**Comment by LGAGELIN** [comment]
Il manque les types de membres de jury.

On n'importe pas les financements pour le moment (because codification spécifique HCERES non déductible)

**Comment by LGAGELIN** [comment]
Modifications effectuées le 18/01/2017 avec Yomgui sur l'import des doctorants :

On exclut les statuts administratifs suivants (colonne LIB_STATUT_ADMINI) :
- Abandon avant inscription
- Dossier clos (abandon)
- Suspension d'études

Si on trouve un établissement "HORSRF" dans CODE_ETAB_ADM : on n'importe pas l'organisation du diplôme antérieur

Pour les personnes qui ont 2 lignes de doctorats, on n'importe qu'une seule ligne (la première trouvée). Personnes concernées :
- Julio BURDMAN
- Nicolas JONAS
=> Il faudra créer le deuxième doctorat manuellement sur la PROD.

Pour le cas de Marie MENDRAS, qui a 1 hdr et un doctorat IEP. Pour pouvoir importer correctement ses diplômes antérieurs, on a  supprimé du fichier d'import l'établissement IEPP de son diplôme antérieur pour la ligne hdr.

Les autres doublons du fichier d'import sont annulés du fait de l'exclusion des statuts administratifs. Il s'agit de :
Nathalie Schmidt
Stéphanie Balme
Elsa Tulmets
