### ISSUE TITLE
loader sur le tableau quand liste vide

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#99]
quand l'API retourne une liste vide, le tableau continue de montrer un loader indéfiniment.
Il faudrait dans ce cas laisser le tableau vide.
Marchera bien si on indique le nombre de lignes dans le tableau dans le footer (relates #100 )

**Comment by Yomguithereal** [comment]
C'est bon, l'architecture des composants a été fixée pour ne pas se baser sur une heuristique de taille du tableau traité.
